---
categories:
- poetry
- translation
- hindi
date: '2021-06-02T14:40:29+05:30'
title: Amrita Pritam – a couple of poems
---

कुफ़्र/ blasphemy

 आज हमने एक दुनिया बेची<br>
और एक दीन ख़रीद लिया<br>
हमने कुफ़्र की बात की

 Today, I have sold off a world<br>
And bought a faith<br>
I have uttered a blasphemy

 सपनों का एक थान बुना था<br>
एक गज़ कपड़ा फाड़ लिया<br>
और उम्र की चोली सी ली

 From the roll of dreams woven,<br>
I tore off a yard of cloth<br>
And stitched a blouse of youth

 आज हमने आसमान के घड़े से<br>
बादल का एक ढकना उतारा<br>
और एक घूँट चाँदनी पी ली

 Today, I have lifted the lid of clouds<br>
From the pot that’s the sky<br>
And took a sip of the moonlight

 यह जो एक घड़ी हमने<br>
मौत से उधार ली है<br>
गीतों से इसका दाम चुका देंगे

 And that one moment<br>
I have borrowed from death<br>
I shall repay, in song

 \*\*\*\*\*\*

 पहचान // Recognition

 Amrita Pritam

 तुम मिले<br>
तो कई जन्म<br>
मेरी नब्ज़ में धड़के<br>
तो मेरी साँसों ने तुम्हारी साँसों का घूँट पिया<br>
तब मस्तक में कई काल पलट गए–

 We met<br>
And many lives of mine<br>
Rang in a heart beat<br>
When my breath drank from yours<br>
Mind passed through aeons

 एक गुफा हुआ करती थी<br>
जहाँ मैं थी और एक योगी<br>
योगी ने जब बाजुओं में लेकर<br>
मेरी साँसों को छुआ<br>
तब अल्लाह क़सम!<br>
यही महक थी जो उसके होठों से आई थी–<br>
यह कैसी माया कैसी लीला<br>
कि शायद तुम ही कभी वह योगी थे<br>
या वही योगी है–<br>
जो तुम्हारी सूरत में मेरे पास आया है<br>
और वही मैं हूँ… और वही महक है…

 There used to be this cave<br>
Where I was and there was a yogi<br>
When he took me in his arms<br>
And touched my breath,<br>
God is my witness!<br>
This same fragrance was on his lips–<br>
What magic is it and what playfulness<br>
May be, at that time, you were that yogi<br>
Or it’s the same yogi<br>
That’s come to me in your guise<br>
But it’s the same me…And it’s the same fragrance…

 (Translation mine)<br>

<!--
post-705
https://venugvgk.wordpress.com/2021/06/02/amrita-pritam-a-couple-of-poems/
-->
