---
categories:
- life-as-it-happens
date: '2010-05-28T09:13:36+05:30'
title: Pennies, Buses and Perspectives
---

In three years of my stay in Delhi, I traveled by buses some 6 times.  There, I told you the fact; now I will leave you to get judgmental about it.

 The other day, I had to go to to Gurgaon where a good lunch and some entertaining conversation was promised. I decided to take a bus telling myself that this is a good chance to get a different perspective on Delhi, as I would be leaving the place soon.

 Yes, I also wanted to save the 600 bucks or so that I would have had to spend if I took a cab. While on saving pennies, my favorite penny\-phrase had been ‘penny pincher’ with the right amount of disdain. And the favorite penny quote used to be  “penny wise pound foolish” implying that all penny pinching is useless. Ever since the newly acquired jobless status, my favorite penny quote changed to “a penny saved is a penny less to be earned”.

 Anyway, this is all about the different perspectives gained in the travel\-to\-Gurgaon\-in\-a\-bus process. Here we go:

 ***The same streets look different when you travel in a bus. Since you are seated higher in a bus, there is actually a physically different perspective.***

 *One gets to be more aware of the surroundings. You get about two seconds to jump out of a bus on a corner if you realize in time that the bus is going left where as you want to go right. Well, this happens primarily because you don’t know anything about bus routes. Therefore, this observation might not apply to people who are more exposed to the intricacies of the said subject.*

 ***The aurobindo ashram herbal garden that you always thought of visiting is a triangular patch of land overgrown with clearly identifiable weeds. You definitely can’t see this unless you are in a bus.***

 *The ‘machine ka thanda pani 50 p’ carts are no anachronisms. When there is no one selling bottled water within a kilometer either way, the ‘MCD south zone 2/15’ written in flaky paint on the ‘machine’ is the only thing that lets you rationalize that there is some sort of MCD registration that this guy has. Thereafter, buying a glass of water is not too far away on the perspectives path, especially since you don’t want to die of thirst.*

 ***In unfamiliar environs, the building you want to go to is generally right after a bus stop. By the time you spot the building, the bus is past. The next stop is at least a kilometer away.***

 *If you walked back to the building you wanted to go, then walked a couple of kilometers to the lunch venue and if you are wearing a jeans and t\-shirt in to a building full of people wearing business formals, you might want to wait outside till your hosts turn up. Otherwise, the reservation desk guy might ask you if you are going inside for the “thandi hawa”. Even if you give a cold, haughty look and walk past that guy, it might come back to haunt you if you discover five minutes later that you are in the wrong joint. The reservation desk guy will have the last laugh/sneer even as you might console yourself with the fact that the ignoramus doesn’t know you are going to the hipper place down the corridor.*

 ***When you start walking back to the bus stop a couple of kilometers away after a satisfying lunch, there are moments when you curse the heat, yourself, the pennies you are trying to pinch and almost pull out your cell phone to call for a cab. At this juncture, if you look around, you might find the middle aged woman bringing a heavy hammer down on an old, rusted iron cylinder repeatedly. If you look closer, you might see that she is trying to take the hardened concrete out of the cylinder, no doubt with an intent to sell the iron for scrap. Now is the time to exercise your legendary analytical skills and try to work out the cost\-benefit of her actions. The result might, just might, persuade you to try walking that one kilometer.***

 *A ride from Gurgaon to Delhi in a Skoda Fabia costs Rs. 20\. You just stand on the road and hope that a Fabia ,with a professional driver (as opposed to a guy driving his own car) in it, turns up.*

 Well, even considering that there were no spirits at the lunch, it was good and the conversation was entertaining as expected (thanks, guys!).  And as you can see, valuable perspectives were gained, documented and dispatched.

<!--
post-72
https://venugvgk.wordpress.com/2010/05/28/pennies-buses-and-perspectives/
-->
