---
categories:
- musings
date: '2010-06-30T21:54:56+05:30'
title: 'Babaspeak: Gambling'
---

Senior Bhakta and one of his juniors in the firm went out for a chai. A group of unkempt looking people were sitting on the kerb and were playing a rustic version of ludo, drawn in dust.

 Senior Bhakta looked disgustedly at them and launched in to a tirade in English, safe in the knowledge that they wouldn’t understand the launguage: “look at them, jobless guys, sitting down to play in dirt and dust…why don’t they do something useful instead of wasting their time? They gamble their lives away and then cry out that they are poor and that the society is not fair. These guys have no sense of what life is worth..” and so on and so forth.

 The junior, well accustomed to these outbursts, observed rhetorically as he lit up: “so, if you just leave out the poverty part of it, how is it different from what we do with our lives, anyway?”

<!--
post-105
https://venugvgk.wordpress.com/2010/06/30/gambling/
-->
