---
categories:
- musings
date: '2016-07-18T11:38:20+05:30'
title: The single biggest reason you are unhappy…
---

…is the easy availability of comparisons. Here is how it goes.

 The grass has always been greener on the other side. In this social age, we get to see the innumerable other sides and the lush green grass on each of them…in real time and with perfect clarity. Obviously, it has not always been like this.

 There was a time when a man was born, lived and died in the same community. He learnt about the life, universe, and everything in it from the community around him. He learnt how to be good, how to live and love. And he would be done learning by the time he was 25, if not sooner.

 Then he lived his life accordingly. His beliefs and his world were in sync and changed slowly enough for them to remain so.

 Periodically, he would learn of other things, from far away places, about people he could hardly relate to. These did not bother him much as he believed these things were beyond his reach and he was beyond their influence. Occasionally, when he felt something more than that, the people around him reminded it was just the grass being greener on the other side. And the other side was too far to reach.

 Today, thanks to the various information and social  products, the other side is never far from your thoughts. Wherever you are, whatever you do and however you live, you always get to see something better, something more productive, something more comfortable. And, here is the key difference, you know that the people on the other side are just like you…you get to see their lives much more closely.  Things are no longer in the realm of the unattainable but you don’t have them. If only you had a little more luck, if only you were a little more rich, if you only you worked a little more harder…you are never really happy with yourself.

 And you will never be if you just spend time working hard for your career, scrolling Facebook feeds and wishing you were happier.

<!--
post-562
https://venugvgk.wordpress.com/2016/07/18/the-difficult-of-being-happy-in-the-social-age/
-->
