---
categories:
- musings
date: '2020-10-25T10:10:38+05:30'
title: Science and Sociology
---

I am learning sociology along with our girl who is in 12th grade. We have an enthusiastic sociology major setting us up with videos and readings, we come prepared with notes and then there is an hour\-long discussion every week. We also spend an hour or more internally, discussing the ideas and thoughts. The following note comes as a reflection from a few of these classes. And yes, this is not my first brush with sociology.

 One of the things I like about sociology is how it deals with the limitations of the approach up\-front. The existence of deep seated biases and prejudices we bring to work as human sociologists, is highlighted and the definition of sociological perspective incorporates the existence of these human limitations. Sociology also acknowledges the limits to its explanatory powers, rather explicitly.

 This is unlike science, which does not highlight these limitations. As a rule, every discipline kind of overstates it’s own explanatory powers, but science as we learnt it, definitely takes the cake. Science presents itself as the explainer of all things in the universe whereas it is not.

 Scientific method is awesome and cool but when we attribute the objectivity of the scientific method to our own process of reasoning, and start behaving like since we are using reason and rationality as a tool, what we arrive at is true and it is the only truth, is when the approach stops being useful.

 Given that most of us are from the couple of generations that venerated science and trivialised social sciences, there is no dearth of people who go about making observations, using logic and reasoning to make conclusions and go around behaving like they have arrived at the truth, all the while unaware of how the lack of sociological and psychological perspective limits the utility of their reasoning very severely.

 So, please learn a little bit of formal sociology and psychology before you go about commenting on social issues. You will only be helping yourself.

<!--
post-716
https://venugvgk.wordpress.com/2020/10/25/science-and-sociology/
-->
