---
categories:
- poetry
- telugu
- autism
- sonta-kavitvam
date: '2018-04-23T09:53:24+05:30'
title: నువ్వూ, నేనూ, ఆటిజం/You, me and Autism
---

I wrote this in Telugu first and now translated into English.

 ఈ కవిత మొదట తెలుగులో రాశాను. ఇప్పుడు ఇంగ్లీషులో.

 **You, me and autism**

 You came into my world<br>
 bringing a small little<br>
 naughty devil along

 Yes, I know,<br>
 I noticed, on and off,<br>
 the shadow of the little one

 As we went along,<br>
 Right in front of my eyes,<br>
 The naughty devil<br>
 Took hold of you, little by little

 One fine morning<br>
 I wake up and notice;<br>
 I can no more tell<br>
 It’s you or the inner devil I see

 Afraid of what’s happening<br>
 I was confused and clueless<br>
 Caught in the throes of passionate love,<br>
 and burning hate,

 But for all of that, my dear,<br>
 You were just about<br>
 Three and half<br>
 And surrounding you,<br>
 Wizards, teachers, relatives,<br>
 Friends and scientists

 In the middle of the raging ocean<br>
 When I looked inward<br>
 right into myself<br>
 A couple of my own devils,<br>
 The ones I had brought along,<br>
 Waved at me, with questioning looks

 And when I looked up and about,<br>
 Small devils grinning<br>
 In the shadows around the aura<br>
 Of every angel around

 That’s when it dawned<br>
 I got to live with the little devil<br>
 If I want you;<br>
 And if I don’t want it,<br>
 Let go of you as well.

 Shaking the sloth off my eyes<br>
 Looked around for you<br>
 And found you going along<br>
 With the devil in tow<br>
 Unsure of footing ,<br>
 Falling, failing<br>
 And getting up yet again

 Ever since,<br>
 I have been,<br>
 Behind you, on your path<br>
 Magic, wizards,<br>
 Teachers, scientists,<br>
 And I standing between<br>
 You and all of them

 Now, when I see you,<br>
 Your own aura all around,<br>
 And in the light of the aura,<br>
 Out in the open, for everyone to see,<br>
 The tussles between you and your devils<br>
 And applause from all around

 Those searching for<br>
 Easy steps to success<br>
 may not get this, but

 “It’s your life, it’s your path<br>
 All I can do is<br>
 Walk with you<br>
 While I am here”<br>
 Me knowing this<br>
 Is the real secret<br>
 Of your success,<br>
 My patience,<br>
 And all the hopes<br>
 blooming on our path.

<br>

 నువు పుట్టుకతోనే<br>
 ఒక చిన్ని భూతాన్ని<br>
 వెంట తీసుకువచ్చావు

 అవును, నాకు తెలుసు<br>
 ఆ భూతపు ఛాయలు<br>
 అప్పుడప్పుడు చూస్తూ వచ్చాను

 పోగా పోగా<br>
 నేను చూస్తూ ఉండగా<br>
 ఆ భూతం నిను కొద్దికొద్దిగా<br>
 ఆక్రమించుకుంది

 ఒక రోజు పొద్దునలేచి చూస్తే<br>
 నా ముందున్నది<br>
 నువ్వో నీ వెంట వచ్చిన భూతమో<br>
 తెలియని పరిస్థితి

 నాకేదో అవుతుందన్న అయోమయం<br>
 ప్రేమార్తి, ద్వేషాగ్నుల కలగాపులగం

 ఇంతా చేస్తే కన్నా<br>
 నీకింకా అప్పటికి<br>
 మూడున్నరేళ్లు<br>
 ఆలోపలే<br>
 నీ చుట్టూ<br>
 పొంచిఉన్న మాంత్రికులు<br>
 టీచర్లు బంధువులు<br>
 స్నేహితులు శాస్త్రజ్ఞులు

 ఆ కల్లోల సాగర మధ్యంలో<br>
 తలవంచుకుని నాలోకి నేను<br>
 తొంగి చూసుకుంటే<br>
 నాతోపాటు భూమ్మీదికి వచ్చిన<br>
 రెండు మూడు భూతాలు<br>
 పలకరింపుగా చేతులూపి<br>
 ప్రశ్నార్థకంగా చూశాయి

 తలయెత్తి చుట్టూ చూద్దును కదా<br>
 ప్రతి దివ్య పురుషుడి<br>
 కాంతి వలయాల నీడలో<br>
 పళ్ళికిలిస్తూ పిల్ల భూతాలు

 అప్పుడర్ధమైంది నాకు<br>
 నువు కావాలంటే<br>
 ఆ భూతంతో కలిసి బతకాలి<br>
 ఆ భూతం వద్దనుకుంటే<br>
 నిను పోతే పొమ్మని<br>
 వదులుకోవాలి

 కళ్ళనులుముకుని<br>
 నీకోసం వెదికితే<br>
 తప్పటడుగులో, తప్పుటడుగులో<br>
 పడుతూ లేస్తూ<br>
 నీ దారి పట్టుకు పోతూ నువ్వు,<br>
 నీ వెంట వచ్చిన భూతమూ

 అప్పటినుంచీ<br>
 నీ దారిలో నీ వెనక<br>
 నీతో వస్తూ ఉన్నాను<br>
 మంత్రాలూ మాంత్రికులూ<br>
 టీచర్లూ శాస్త్రజ్ఞులూ<br>
 నీకు వాళ్ళకీ<br>
 మధ్యలో నేను

 ఇప్పుడు చూద్దును కదా<br>
 నీ చుట్టూ కాంతి వలయాలు<br>
 ఆ కాంతిలో బాహాటంగా బహిరంగంగా<br>
 నీకూ భూతాలకూ బాహాబాహీలు<br>
 అందరూ నిను చూసి ఆహా ఓహోలు

 విజయానికి సులువైన<br>
 మెట్లదారులు వెతికేవాళ్ళకి<br>
 చెప్పినా తెలుసుకోలేరు కానీ

 “నీ బతుకు నీది నీ దారి నీది<br>
 నే ఉన్నన్నాళ్లు నీతో కలిసి<br>
 నడవడమే నేను చేయగలిగేది”<br>
 ఇది నాకు తెలిసిరావడమే<br>
 నీ విజయానికీ<br>
 నా సంయమనానికీ<br>
 మనం నడుస్తున్న దారిలో<br>
 ఆశలు చిగురించడానికీ<br>
 అసలు కారణం.

 \*\*\*\*

 ఆటిజం గురించి:

 ఏప్రిల్ నెలలో ప్రపంచ వ్యాప్తంగా ‘ఆటిజం’ గురించి అవగాహన పెంచే కార్యక్రమాలు జరుగుతుంటాయి. ఆటిజం నాడీ వ్యవస్థలో మార్పుల వల్ల కలిగే ఒక మానసిక స్థితి. దీనికి కారణాలు పూర్తిగా తెలియవు, కాబట్టి మందులు లేవు. పిల్లలకి రెండు నుంచి నాలుగు సంవత్సరాల వయసులో ఆటిజం ఉందని గుర్తించవచ్చు. బిహేవియరల్ థెరపీ ద్వారా పిల్లలకి కావలసిన ప్రవర్తన నేర్పడం ఇప్పటికి అందుబాటులో ఉన్న మార్గం.

 రెండు నుంచి నాలుగేళ్ళ మధ్య వయసులో తమ కొడుక్కో, కూతురుకో ఆటిజం ఉందని తెలుసుకున్న తల్లిదండ్రులు పడే ఆవేదన, ఆందోళన వర్ణనాతీతం. నీ కట్టుబొట్టు వేరుగా ఉంటేనే నువ్వు నాకు శత్రువువి అన్నట్లు చూసే ప్రపంచంలో, నాడీ వ్యవస్థలు, జ్ఞానేంద్రియాల పనితీరు, మానసిక స్థితులు వేరుగా ఉండే పిల్లల్ని పెంచడం చాలా ఒత్తిళ్ళకు గురిచేస్తుంది. ఈ పిల్లలకి మాట్లాడడం, అనుకున్నది చెప్పగలగడం, కావాల్సింది అడగడం, తమ చుట్టూ ఉండే పెద్ద, చిన్న వాళ్లతో కలిసి ఉండగలగడం వంటివి – మిగతా పిల్లలు సహజ సిద్ధంగా నేర్చుకునే చాలా సామర్థ్యాలు – పనిగట్టుకుని నేర్పించాల్సి వస్తుంది. చాలా థెరపీలు అవసరమవుతాయి.

 పిల్లలతో, పిల్లలకోసం ఎంతో సమయం, శ్రమ, డబ్బు పెట్టవలసి రావడం ఒక రకం కష్టం అయితే, తమ మీద, తమ పిల్లల మీద, భవిష్యత్తు మీద తాము పెంచుకున్న కలల్ని తిరిగి ఊహించుకుని, తమ జీవితాల్ని తిరిగి నిర్మించుకోవాల్సి రావడం ఇంకా పెద్ద కష్టం. చుట్టూ తాము ఊహించుకున్న సమాజమూ, ఆ సమాజపు పోకడలు, తమకి, తమ పిల్లలకీ సరిపడవని తెలుసుకుని, ఆ తర్వాత ఆ తెలివిడికి తగ్గట్లుగా పిల్లలకి ఉపయోగపడే నిర్ణయాలు తీసుకుని, వాటి ప్రకారం బతకడం ఎంత కష్టమో ఊహించడం సులభమే.

 ఇప్పటివరకూ ఇది తల్లిదండ్రుల గురించే. అంత చిన్న వయసు నుండి ఈ ఆవేదనలు, ఆందోళనలు, తుఫానుల నట్టనడుమ పెరుగుతున్న పిల్లలు ఎలా నెట్టుకొస్తున్నారనేది ఊహకు అందని విషయం.

 అటువంటి ఒక పిల్లాడికి తండ్రిని నేను.

<!--
post-616
https://venugvgk.wordpress.com/2018/04/23/%e0%b0%a8%e0%b1%81%e0%b0%b5%e0%b1%8d%e0%b0%b5%e0%b1%82-%e0%b0%a8%e0%b1%87%e0%b0%a8%e0%b1%82-%e0%b0%86%e0%b0%9f%e0%b0%bf%e0%b0%9c%e0%b0%82/
-->
