---
categories:
- poetry
- translation
- telugu
date: '2021-08-09T09:09:26+05:30'
title: LOVE AFTER LOVEby Derek Walcott
---

ప్రేమ తరువాయి ప్రేమ

 నీ గది గుమ్మంలో, నీ సొంత అద్దంలో<br>
నిన్ను నువ్వే చూసుకుని<br>
ఆనందోత్సాహాలతో<br>
పలకరించుకునే ఒక రోజు వస్తుంది

 ఒకరి స్వాగతాన్ని చూసి ఇంకొకరు,<br>
మీరిద్దరూ చిరునవ్వులు నవ్వుకుని<br>
‘రా, కూర్చో, కొంచెమేలే, తిను,’<br>
అనుకుంటారు ఆప్యాయంగా.

 ఇన్నాళ్లు అపరిచితుడిగా మిగిలిపోయిన నిన్ను నువ్వు<br>
మళ్ళీ ప్రేమిస్తావు, అన్న పానీయాలిచ్చి ఆదరిస్తావు<br>
ఒకప్పుడు నిన్ను ప్రేమించిన ఆ అపరిచితుడికి,<br>
నీ హృదయాన్ని, తనకు తానే, ఇచ్చేసుకుంటావు

 ఇన్నాళ్ళ జీవితంలో ఇంకొకరి కోసం<br>
నువు నిర్లక్ష్యం చేసిన అపరిచితుడు<br>
నువ్వేమిటో కంఠోపాఠంగా తెలిసినవాడు.

 పుస్తకాల అరలోంచి ప్రేమలేఖలు తీసి పారేసి,<br>
పాత ఫోటోలు, తెగించి రాసిన సందేశాలు,<br>
నీకై నువు నిర్మించుకున్న బింబాల్ని అద్దం నుంచి వలిచి వేసి,<br>
కూర్చో. జీవితాన్ని ఆస్వాదించు.

 The time will come<br>
when, with elation,<br>
you will greet yourself arriving<br>
at your own door, in your own mirror,<br>
and each will smile at the other’s welcome,<br>
and say, sit here. Eat.

 You will love again the stranger who was your self.<br>
Give wine. Give bread. Give back your heart<br>
to itself, to the stranger who has loved you

 all your life, whom you ignored<br>
for another, who knows you by heart.<br>
Take down the love letters from the bookshelf,

 the photographs, the desperate notes,<br>
peel your own image from the mirror.<br>
Sit. Feast on your life.

<!--
post-778
https://venugvgk.wordpress.com/2021/08/09/love-after-loveby-derek-walcott/
-->
