---
page-layout: full

listing:
  - id: work
    template: _themes/experience.ejs
    contents: work.yml

---
# Profile Summary

I am a nonprofit leader focused on building and running high-performance teams in the education/alternative living space. 

Currently, I lead Farm Hill Education Trust (FHT), a non-profit working in the areas of education, neurodiversity and community. Through FHT, we run subodha, a homeschool support center and Sambahvam, an early intervention center, in Bangalore. We also run Farm Hill Learning, a neurodiversity, close to nature learning community, near Hosur. 

As a freelance consultant, I also advise education firms and non-profit teams on organizational development, project formulation, implementation, monitoring and impact assessment.

In the past, I was a core member in an ed-tech startup team where I played an instrumental role in designing, implementing and selling an innovative assessment product for educational institutions.

Additionally, at different points during my professional career, I taught Electrical Engineering at undergraduate level, picked up an MBA at the IIM Bangalore, was a management consultant, became an Autism Dad, coached CAT students, wrote a couple of picture books for children and translated a few children’s books into Telugu.


# Experience

::: {#work}

:::



# Education
```{=html}
<div style="text-align:center;">
            <span style="float:left"> Tata Institute of Social Sciences </span>
            <span style="float:right"> 2024 - present </span>
            <span style="text-align:center"> M.A (El.Ed.)   </span>
            <br><br>
        </div> 

<div style="text-align:center;">
            <span style="float:left"> IIM Bangalore</span>
            <span style="float:right"> 2005 - 2007 </span>
            <span style="text-align:center"> &emsp; &emsp;&emsp;&emsp;PGDM   </span>
            <br><br>
        </div> 

<div style="text-align:center;">
            <span style="float:left"> Osmania University </span>
            <span style="float:right"> 1998 - 2002 </span>
            <span style="text-align:center"> &emsp; B.E.  </span>
            <br><br>
        </div> 

<div style="text-align:center;">
            <span style="float:left"> Jawahar Navodaya Vidyalaya </span>
            <span style="float:right"> 1990 - 1995 </span>
            <span style="text-align:center">  Schooling  </span>
            <br><br>
        </div> 
```


