---
title: Venu's notes
publish: false
---
session 7 - computer guesses the number - binary search in operation
session 8 - prime numbers in a range - is_prime(n) and primes_in_range(start, end)
session 9 - coin toss simulator - random.randint(0, 1) and fractions of heads and tails
session 10 - two-dice-sum game


- All factors of a number
- Perfect numbers and abundant/deficient numbers
- Prime factors of a number
- Digit sum and divisibility checks (e.g., check if a number is divisible by 3, 9, or 11 using digit patterns)
- Base conversions in a constrained way (e.g., convert numbers between base 10 and base 2 for small values)
- Polygon angle checker: given number of sides n, compute interior angle sum and compare it with a claimed sum.
- WORDLE??
- Reverse and palindrome checker



With coin toss expectation is that we will reach 50:50 over a large number of tosses. 

With dice toss, the expectation is - each number (1-6) should appear with equal frequency over a large number of rolls.

When you toss two dice, what happens?

2,3,4,5,6,7,8,9,10,11,12 

2 - 1 way (1,1)
3 - 2 ways (1,2), (2,1)
4 - 3 ways (1,3), (2,2), (3,1)
5 - 4 ways (1,4), (2,3), (3,2), (4,1)
6 - 5 ways (1,5), (2,4), (3,3), (4,2), (5,1)
7 - 6 ways (1,6), (2,5), (3,4), (4,3), (5,2), (6,1)
8 - 5 ways (2,6), (3,5), (4,4   ), (5,3), (6,2)
9 - 4 ways (3,6), (4,5), (5,4), (6,3)
10 - 3 ways (4,6), (5,5), (6,4)
11 - 2 ways (5,6), (6,5)                
12 - 1 way (6,6)

Relative frequencies of sums of two dice:
- 2 - 1/36  
- 3 - 2/36
- 4 - 3/36
- 5 - 4/36
- 6 - 5/36                  
- 7 - 6/36
- 8 - 5/36
- 9 - 4/36
- 10 - 3/36
- 11 - 2/36
- 12 - 1/36 


