---
title: Most philosophers were bachelor men
categories: 
 - philosophy
date: 2025-02-15
---

Mary Midgley 


None of these [great] philosophers … had any experience of living with women or children, which is, after all, quite an important aspect of human life. I wrote [‘Rings and Books’] drawing attention to this statistic and asking whether it might not account for a certain over-abstractness, a certain remoteness from life, in the European philosophical tradition.

Descartes concludes that the only thing I can know with certainty is that I am thinking (and therefore that I exist) – or, as philosophers know it, Cogito, ergo sum. Summarised by Midgley: ‘Here I am, said Descartes, a soul, an isolated thinker.’ But, despite its prominence in canonical histories of Western thought, Midgley was not overly impressed by this argument. In fact, she thinks this Cartesian move is born from the philosophical ‘adolescence’ that Descartes never grew up from. As she puts it:

People leading a normal domestic life would not, I believe, have fallen into this sort of mistake. They would have taken alarm at the attitude to other people which follows from Descartes’s position. For Descartes, other people’s existence has to be inferred, and the inference is a most insecure one … Now I rather think that nobody who was playing a normal active part among other human beings could regard them like this. But what I am quite sure of is that for anybody living intimately with them as a genuine member of a family … their consciousness would be every bit as certain as his own.
Midgley’s use of ‘normal’ here is no doubt reminiscent of a dated view about the nuclear family hailing from a time when many women carried out most of the domestic duties. But even aside from this, Midgley’s claim is important. As knowers, Midgley sees many of us (if not all) as already entangled in our close relations with others. From here, we can learn about the world, including the certain existence of other people. And Midgley thought that the experiences of those caring for children, in particular, could help illuminate the extent to which we really are entangled with one another’s existences.

https://aeon.co/essays/for-mary-midgley-philosophy-must-be-entangled-in-daily-life?fbclid=IwY2xjawIc6vpleHRuA2FlbQIxMQABHQKeYu8vC1lBZ1mZkMlw8B10faQOdrE-n0uQeCgqs_LSUsIubWmTHPH9CA_aem_LOgQHiS_cT1zueyire6fDg

