---
categories:
- musings
date: '2011-07-19T13:00:19+05:30'
title: 'Babaspeak: On Work'
---

I have been working hard in the last two weeks – at least I feel that way, may be as I have come back to consulting after a year of happily teaching English classes. So, the idea of work has been on my mind and here is a collection of “work quotes” from IIMBaba’s teachings and discourses over the years. You know where that preachy tone comes from.

 ***“******Work is like a python – when you are in its clutches, if you continue to stare at it mesmerized, it will slowly crush you. The trick is to get out of its grip, a little at a time******”***

 (Same approach works for depression, too)

 ***“Why do you want work life balance? They should not be weighed in the same scales at all”***

 ***“If you think the feeling you get when there is a lot of work waiting for you is bad, wait till the time when all that is waiting for you is non\-work\*”***

 ***“Are you one of those who say they will be happy if only they can make a living out of doing whatever they think they like doing? Nothing can be far from the truth. By making your pleasure your work, instead of making work more palatable, you are going to make the pleasure much less pleasurable. It’s the label “work” that makes it painful, not what it is”***

 ***“Why do you want your work to be ‘meaningful’ and ‘fulfilling’? It’s your life which is supposed to have these attributes. Stop expecting salvation through work. Treat it as the small part of life that it is. At 30, work does look like a large part of life, just like sex looked like a large part of marriage when you were 25 (or 20 or 18 depending on when you started contemplating marriage).  Out grow this work dependence, start living life”***

 There. Now that you have been suitably enlightened, please get back to work.

 \*Non\-work: work like things done in offices around the world when there is no work.

<!--
post-402
https://venugvgk.wordpress.com/2011/07/19/babaspeak-on-work/
-->
