---
categories:
- musings
date: '2017-04-11T08:25:44+05:30'
title: Midlife thoughts, mid-week
---

***“Failing at something you really want to do should be worth more than succeeding at anything else.”***

 When you start something, you start with a bunch of ideals, you want to be different from everyone else.

 You start working and you come in contact with people. You work for them, you work with them. As you go and grow, you will come across people and situations where your idealism and your urge to do good seems to be a disadvantage.

 A point comes where you are overwhelmed by the number of times this is happening. You start thinking about snatching the advantage back. You start questioning the practicability of your ideals.

 That point is the real test of your fortitude, your commitment to what you really want to do. The easy path is to turn into everyone else.

 That path will eventually lead to failure. Have no doubt about that. You may ‘succeed’ but that ‘success’ will not be at what you really wanted to do. It would be a completely different goal, even when you score it.

 That is the time to think hard and look close. Choose the people and situations you work with. Grow slowly. Focus on building a community of like\-minded people. You will notice the ‘overwhelming number of times’ go down to manageable levels. With any luck, they will eventually disappear.

 While all of this happens, hang in. Take care of yourself and your well\-wishers. At the same time, be ready to let go. Failing at something you really want to do should be worth more than succeeding at anything else.

 Have a great year!

<!--
post-580
https://venugvgk.wordpress.com/2017/04/11/midlife-thoughts-mid-week/
-->
