---
categories:
- books
- musings
date: '2010-12-26T18:09:13+05:30'
title: Dead Beat, Donaghy, Prelutsky and poetry
---

I have just finished reading **Dead Beat: Lost Souls, Lucky Stiffs and The Perverse Pleasures of Obituaries** by Marilyn Johnson. It’s an interesting book, written with obvious relish and enthusiasm. The author is an obit writer herself and writes mostly about the art/science of obituary writing, as understood and represented by a host of (apparently) well known obituary writers in the UK and the USA.

 The subject of death, one would think, cannot be far when writing about obituaries. Surprisingly, The book steers completely clear of the topic. There is absolutely no philosophizing about life, death, meaning and all. I am willing to concede that an obituary is more about life than about death; but it is hard to imagine that not one of the obituary writers is interested in discussing Death, let alone confess to being captivated or motivated by the spectacle it can get to be. Or may be such morbid (!) thoughts get edited out!

 So, the author focuses on the people who write obituaries – the trend setters, the game changers and their perspectives. For about half of the book it reads fine. And she gives some very good examples of witty and interesting obits. Then, more of the same. Then, she talks about her own obsession with obituaries, internet news groups dedicated to obituary writing and reading and fellow obit fans. At which point, I kind of lost the flow.

 (**update:** I must confess that the book made me curious about obituaries and I have been looking for good ones. I guess [this one](http://www.telegraph.co.uk/news/obituaries/law-obituaries/8220386/His-Honour-James-Pickles.html) of His Honour James Pickles in The Telegraph would appeal to obit fans)

 Going off on a tangent, one of the people whose obit she mentions is [Michael Donaghy](http://en.wikipedia.org/wiki/Michael_Donaghy), an award winning poet and musician. I looked him up. [Here](http://famouspoetsandpoems.com/poets/michael_donaghy/poems/7843) is a link to one of his poems. [Here](http://www.poetryarchive.org/poetryarchive/singlePoet.do?poetId=145) is one more profile piece and more poems you can listen to. Guy writes deep, very deep.

 One more tangent: The famous poets page link where I found Donaghy’s poem has a pane on the left with more names of famous poets. One of the names I did not recognize was that of Jack Prelutsky. so, I clicked on the name and found the following poem.

 **Be Glad Your Nose is on Your Face** by **Jack Prelutsky**   Be glad your nose is on your face,

 not pasted on some other place,

 for if it were where it is not,

 you might dislike your nose a lot.

 Imagine if your precious nose

 were sandwiched in between your toes,

 that clearly would not be a treat,

 for you’d be forced to smell your feet.

 Your nose would be a source of dread

 were it attached atop your head,

 it soon would drive you to despair,

 forever tickled by your hair.

 Within your ear, your nose would be

 an absolute catastrophe,

 for when you were obliged to sneeze,

 your brain would rattle from the breeze.

 Your nose, instead, through thick and thin,

 remains between your eyes and chin,

 not pasted on some other place–

 be glad your nose is on your face!

  Brilliant, I say! More of the same [here](http://famouspoetsandpoems.com/poets/jack_prelutsky/poems). While we are on brilliant poetry, let me present one more.

  In the instantaneous silence,

 I closed my eyes for a moment

 In the shade of a blue cliff

 In the middle of a vast wilderness

 A small tick ticking sound

 And a wink winking blink

 A creepy smell of burning

 And a hint of malevolence

 The blue cliff gave off a roar

 Tick ticking is now burr burring

 The wink winking waned off

 The monsters have materialized

 Got to go, the light has turned green.

  The identity of the poet will be revealed on request, after running a background check to ascertain your intentions. Please put your request in the comments section.<br>

<!--
post-293
https://venugvgk.wordpress.com/2010/12/26/dead-beat-donaghy-and-prelutskys-poetry/
-->
