---
categories:
- poetry
- translation
- telugu
date: '2020-04-23T15:48:44+05:30'
title: The First Geniuses/ఆదిమ మేధావులు
---

<br>
by Billy Collins

 It is so early almost nothing has happened.<br>
Agriculture is an unplanted seed.<br>
Music and the felt hat are thousands of years away.<br>
The sail and the astrolabe, not even specks on the horizon.<br>
The window and scissors: inconceivable.

 దాదాపుగా ఇంకా ఏమీ జరగని<br>
పురాతన కాలపు మొదటి రోజుల్లో,<br>
వ్యవసాయం ఇంకా నాటని విత్తనమే<br>
సంగీతమూ, తలపాగాలూ వేలయేళ్ళ తరువాతే<br>
తెరచాపలూ, నక్షత్ర యంత్రాలూ<br>
దిగంతాల అంచుల్లో కూడా కానరావు<br>
కిటికీలు, కత్తెరలూ ఊహించటానికే లేదు

 But even now, before the orchestra of history<br>
has had time to warm up, the first geniuses<br>
have found one another and gathered into a thoughtful group.<br>
Gaunt, tall and bearded, as you might expect,<br>
they stand outlined against a landscape of smoking volcanoes

 అప్పటికే,<br>
చరిత్ర తన కచేరీకి ఇంకా సరిగమలు సర్దుకోకముందే,<br>
బుద్ధి కుశలురైన ఆదిమ మేధావులు కొందరు<br>
ఒకరినొకరు కలుసుకున్నారు

 పొగలు చిమ్మే అగ్నిపర్వతాల వెలుతురులో<br>
ఎత్తుగా, గడ్డాలతో, బక్కచిక్కి,<br>
రేఖామాత్రంగా కనిపిస్తున్నారు వాళ్ళు

 or move along the shores of lakes, still leaden and unnamed,<br>
or sit on high bare cliffs looking like early arrivals<br>
at a party the earth is about to throw<br>
now that the dinosaurs have finally cleared the room.

 ఒక్కోసారి<br>
చిక్కటి, బరువైన, ఇంకా పేర్లు లేని<br>
సరస్సుల తీరాల వెంట నడుస్తుంటారు

 ఇంకోసారి<br>
రాక్షసబల్లులు ఖాళీ చేసి వెళ్లిన గదిలో<br>
భూమి ఇంకా మొదలుపెట్టని సంబరాలు<br>
చూడటానికి ముందే వచ్చిన వాళ్ళలా<br>
ఎత్తైన మొండి కొండచరియల మీద కూర్చుని ఉంటారు.

 They have yet to discover fire, much less invent the wheel,<br>
so they wander a world mostly dark and motionless<br>
wondering what to do with their wisdom<br>
like young girls wonder what to do with their hair.

 ఇంకా నిప్పునే రాజెయ్యలేదు వాళ్ళు<br>
చక్రాలూ, బండ్లూ చేసేది ఇప్పుడే కాదు<br>
అమ్మాయిలు తమ జుట్టుతో<br>
ఏం చేయాలో తోచక సతమతమైనట్టు,<br>
ఏమీ కదలిక లేని ఆ చీకటి ప్రపంచంలో<br>
తమ జ్ఞానంతో ఏం చేయాలో ఆలోచిస్తూ,<br>
ఏమీ తోచనట్లు తిరుగుతూ ఉంటారు వాళ్ళు

 Once in a while someone will make a pronouncement<br>
about the movement of the stars, the density of silence,<br>
or the strange behaviour of water in winter,<br>
but there is no alphabet, not a drop of ink on earth,<br>
so the words disappear into the deep green forests<br>
like flocks of small, startled birds.

 ఉండీ ఉండీ ఒకళ్ళు<br>
నక్షత్రాల కదలికల గురించో, నిశ్శబ్దపు చిక్కదనం గురించో<br>
లేదా చలికాలంలో నీళ్ల విచిత్ర ప్రవర్తన గురించో<br>
ఒక అభిప్రాయం ప్రకటిస్తారు<br>
అప్పటికింకా అక్షరాలు లేవు<br>
భూమిమీద ఒక్క చుక్క సిరా లేదు<br>
ఎందుకో బెదిరి, ఎగిరి పోయి, దాక్కునే చిన్న పక్షుల గుంపులా<br>
ఆ మాటలు, దట్టమైన పచ్చటి అడవుల్లోకి అదృశ్యమై పోతాయి

 Eventually one of them will come up with the compass<br>
or draw the first number in sand with a stick,<br>
and he will let out a shout like Archimedes in his tub<br>
and curious animals will look up from their grazing.

 పోగా పోగా ఒకరోజు<br>
వాళ్లలో ఒకళ్ళు దిక్సూచిని తయారు చేస్తారు<br>
లేదా ఇసుకతో కర్రపుల్లతో మొదటి అంకె గీస్తారు<br>
ఆర్కిమెడీస్ తొట్టిలోనుంచి అరిచినట్టుగా<br>
అతనొక అరుపు అరుస్తాడు<br>
పచ్చిక మేస్తున్న జంతువులు<br>
కుతూహలంగా తలలెత్తి చూస్తాయి

 Later the water screw and the catapult will appear;<br>
the nail, the speedometer and the bow tie will follow.<br>
But until then they can only pace the world gravely,<br>
knowing nothing but the thrumming of their minds,<br>
not the whereabouts of north or the notion of zero,<br>
not even how to sharpen a stone to a deadly point.

 తర్వాత్తర్వాత నీటి యంత్రాలూ, ఒడిసెలలూ వస్తాయి<br>
ఆ వెనుకనే మేకులూ, వేగమానినులూ<br>
భుజాల మీద కండువాలూ<br>
అప్పటిదాకా వాళ్ళు<br>
తమ మేధస్సుల ప్రకంపనలు తప్ప<br>
ఉత్తర దిక్కు ఎక్కడో, సున్నా అంటే ఏమిటో,<br>
కనీసం ఒక రాయిని ములుకుగా పదునుపెట్టటం ఎలాగో,<br>
తెలియకుండా, గంభీరంగా, ప్రపంచమంతా తిరగవలసిందే!

<!--
post-723
https://venugvgk.wordpress.com/2020/04/23/the-first-geniuses-%e0%b0%86%e0%b0%a6%e0%b0%bf%e0%b0%ae-%e0%b0%ae%e0%b1%87%e0%b0%a7%e0%b0%be%e0%b0%b5%e0%b1%81%e0%b0%b2%e0%b1%81/
-->
