---
categories:
    - literature
date: 2023-12-10
title: నాన్నగారి శతకానికి ముందుమాట
---

ఈ గ్రంథకర్త నాగేశ్వర రాజు గారు నాకు కవిగా కన్నా, నాన్నగారుగానే
ఎక్కువ తెలుసు. ప్రతి కొడుకూ చిన్నప్పుడు తండ్రిని సకల గుణాభిరాముడైన కథా నాయకుడిగా చూస్తారని, తమ కౌమార యవ్వన దశల్లో అదే తండ్రిని ఎందుకూ పనికిమాలిన వాడిగా పరిగణిస్తారనీ, తమ యవ్వనం కనుమరుగు అవుతుండగా ఈ రెండు విపరీతాలు కాక  ఎంతో కొంత నిష్పక్ష పాతంగా వారి గుణ దోష విచారణ చేయగలుగుతారనీ అంటారు. నా జీవితంలో అటువంటి సమయంలో ఈ ముందుమాట రాసే అవకాశం కలగడం నా సుకృతం. 

రాజుగారు గుంటూరు జిల్లా సత్తెనపల్లి దగ్గర పాలడుగు గ్రామంలో, శివరామరాజు, గోవిందమ్మ దంపతులకు జన్మించారు. ఆ కుటుంబానికి కలిగిన ఎనిమిది మంది సంతానంలో వీరే పెద్దవారు. వారి తండ్రిగారైన శివరామరాజుగారు, తన తమ్ముళ్ళతో కలిసి హరికథలు చెప్పేవారు. ఊరూరూ తిరిగి హరికథలు చెప్పి వస్తే,  మూడు నాలుగు నెలలు కుటుంబం గడిచి పోయేది. మిగిలిన కాలం గడ్డుకాలమే. మంచినీళ్లు తాగి కడుపు నింపుకునే రోజులు. 

అటువంటి పరిస్థితుల్లో రాజుగారు చదువుకోవాలని సంకల్పించారు.
సంపద లేకపోయినా ఊళ్ళో మంచి కుటుంబం అనిపేరు, ఎవరో పూర్వీకుల దాతృత్వానికి గుర్తుగా ఊళ్ళో రామాలయంలో సీతా రాముల కళ్యాణానికి మొదటి తలంబ్రాలు ఈ ఇంటినుండి వెళ్ళే సంప్రదాయము, బ్రహ్మం గారి మఠం అనే చిన్న గుళ్ళో పూజారుల హోదా, ఇంట్లో రోజూ పలికే పాండిత్యము, వెరసి సాహసించారు. 

కొన్నిరోజులు రోజుకు ఎనిమిది మైళ్ళు నడిచారు, మూటలు మోశారు, పొలం పనులు చేశారు, సోడాలు అమ్మారు. రెండు మూడు సార్లు చదువు ఆపేసినంత పని అయినా, ఏదో ఒక రకంగా కొనసాగింపు దొరికేది. ఎక్కడ ఎవరు ఉచితంగా చదువు చెబితే, అక్కడ చదువుకున్నారు. సంక్షేమ వసతి గృహాల్లో ఉన్నారు, బంధువుల పంచన చేరారు. అయితే చదువు దెబ్బతినకుండా చూసుకున్నారు. సాధారణంగా క్లాసు ఫస్ట్ తెచ్చుకునే వారు. ఎలాగైతేనేం భాషా ప్రవీణ, టీచర్ ట్రైనింగ్ పూర్తిచేసుకుని చదువు ముగించారు. ఆ గ్రామంలో రెండు వీధుల నిండా ఉన్న బంధుమిత్ర సమూహంలో వీరే మొదటి గ్రాడ్యుయేట్. 

ఉద్యోగానికి దారిలేని పరిస్థితుల్లో మళ్లీ పొలం పనులు చేసుకుంటుండగా అప్పటిలో ఉప్పలపాడు గ్రామ వాస్తవ్యులైన అనంత రామరాజు గారి దృష్టికి వచ్చారు. రామరాజు గారు అప్పటికే టీచరుగా పని చేస్తున్నారు. వారి తండ్రి గారైన సరికొండ హనుమంతరాజు గారు కవి, పండితులు, ఆయుర్వేద వైద్యులు, హనుమద్రామాయణ గ్రంథకర్త. రామరాజు గారు తమ కుమార్తె అంజనీ దేవిని నాగేశ్వర రాజు గారికి ఇచ్చి వివాహం చేశారు. 

వివాహానంతరం కూడా చిన్నా చితకా పనులు చేయవలసి వచ్చింది. విజయవాడలో బంధువుల దుకాణంలో బ్యాగులు కూడా కుట్టారు. చివరికి అనేక ప్రయత్నాల తర్వాత తెలుగు పండితులుగా టీచరు ఉద్యోగం లభించింది. 

ఉద్యోగం వచ్చినంత మాత్రాన జీవితం స్థిరమయిపోయినట్టు కాదు కదా! అప్పటికి కుటుంబం మొత్తంలో రాజుగారు ఒక్కరే ఒక దారికి వచ్చి ఉన్నారు. అప్పటి నుంచీ, కుటుంబంలోనూ, బంధుమిత్ర సమూహంలోనూ, చదువుకునే పిల్లలకు, వ్యవసాయమో, వ్యాపారమో చేసుకుంటున్న కుటుంబాలకు, అనేకానేక అవసరాలకు అండగా ఉన్నారు. చెల్లెళ్ళు, తమ్ముళ్ళ చదువులు, ఉద్యోగాలు, కుటుంబాలతో పాటు, ఇద్దరు తమ్ముళ్ళ అకాల మరణాలను కూడా తన కళ్ళతో చూశారు. ఎన్నెన్నో ఒడి దుడుకులు ఎదురైనా, తనను పుట్టించిన కుటుంబానికి, తను సృష్టించిన కుటుంబానికి కర్తవ్య బద్ధులుగా ఉన్నారు. వారి కుమారులమైన మా ముగ్గురికీ విలువలతో కూడిన జీవన విద్యను అందించారు. ఈ ప్రయాణంలో మా అమ్మగారైన అంజనీ దేవిగారు నెరపిన సహధర్మచర్యం ఎంతో ముఖ్యమైన పాత్ర పోషించింది. 

నాన్నగారి జీవితంలోని ఒడిదుడుకులను మేమందరం కూడా ఎంతో కొంత అనుభవించాము. అయితే వాటిలో ఒక అనుభవం నాపైన ఎంతో ప్రభావం చూపిన కారణంగా దానిని ఇక్కడ ప్రస్తావించకుండా ఉండలేక పోతున్నాను. నేను నాలుగో తరగతి చదివే రోజుల్లో కొన్ని అనివార్యమైన ఆర్థిక ఒత్తిడుల వల్ల నాన్నగారు ఉంటున్న ఇంటిని అమ్మవలసి వచ్చింది. ఊరికి ఒక వైపున, ఇతర మధ్యతరగతి కుటుంబీకుల మధ్యలో కోరి కట్టుకున్న ఇంటిని అమ్ముకుని, ఆ ఊరికి ఇంకొక చివర పేదల కోసం ప్రభుత్వ భూమిలో కమ్యూనిస్టులు సృష్టించిన కాలనీలో ఆరు వందల చదరపు అడుగుల నేలలో అడుగుపెట్టాము. మేమందరం మట్టి కలిపితే, నాన్నగారు తన చేతులతో గోడలు కట్టినట్లు నాకింకా జ్ఞాపకం. ఇంటి పూరికప్పు కూడా తను ఎక్కి కప్పారు. ఇంతకీ ఆ ఇల్లు ఒకటే గది. అందులో మేము ఆరుగురం, మాతో పాటు సెలవులకు వచ్చిపోయే ఇంకో ముగ్గురు. ఎటువంటి సౌకర్యాలూ లేవు.  ఆరేడు వీధులు, వీధికి దాదాపు ఇరవై ఇండ్లూ ఉన్న కాలనీ మొత్తానికి, రెండు చేతి పంపులు. స్నానాల గది బయట గుంట తవ్వుకుని అది నిండితే ఎత్తిపోసుకోవటమే. ఆ గది
తలుపు గోనె పట్టల పరదా. 

అక్కడ అనుభవించిన కష్టాలకన్నా, తెలుసుకున్న నిజాలు ఎక్కువ. ఆ పరిస్థితుల్లో అమ్మ, నాన్నగారు ప్రవర్తించిన పద్ధతి వల్ల నేను నేర్చుకున్న విలువలు నన్ను జీవితంలో చాలా ప్రభావితం చేశాయి. మా ఇరుగు పొరుగు అంతా శ్రమ జీవులు. ఒకాయన రిక్షా తొక్కేవారు. ఇంకొకరు లారీ డ్రైవర్. క్రైస్తవులు, మహమ్మదీయులు, హిందువులు అందరూ పక్కపక్కనే ఉండేవారు. అమ్మా, నాన్నగారు ఎప్పుడూ ఎవరినీ తక్కువగా మాట్లాడటం, ఎవరినీ దూరంగా ఉంచటం, నాకు తెలీదు.  మనుషుల జాతి, మతము, సంపదతో సంబంధం లేకుండా అందరినీ గౌరవంగా చూడటం, కలిసి ఉండటం, తిండీ తిప్పల విషయంలో వివక్ష చూపించకపోవటం, ఇటువంటి విలువలు అక్కడే నేర్చుకున్నాను. ఇంకా ముఖ్యంగా, డబ్బు, సౌకర్యాలు లేకుండా శారీరక శ్రమ చేస్తూ బతుకుతూ కూడా సంతోషంగా ఉండవచ్చునని చూసాను. మనకి ఉన్నది పక్క వాళ్ళతో పంచుకోవటంలో ఆనందం అనుభవించాను. మనలా ఉండని వాళ్ళంటే భయమో, చిన్న చూపో లేకుండటం, మన పనులు మనం చేసుకోవటం, శ్రమకు వెనకాడక పోవటం, ఎవరితోనైనా కలిసి పనిచేయగలం అన్న నమ్మకం, ఇలాంటివి ఎవరూ ప్రబోధించనవసరం లేకుండా సులువుగానే పట్టుబడ్డాయి. 

ఒక పల్లెటూళ్ళో పేద కుటుంబంలో పుట్టి, ఈ ఆటుపోట్ల మధ్యలో, అందరికీ అందుబాటులో ఉంటూ మెల్లగా మధ్య తరగతికి చేరే క్రమంలో రాజుగారు తన సాహిత్యాభిలాషను మాత్రం వదిలిపెట్టలేదు. ఎప్పుడూ చదువుతూ రాస్తూ ఉండేవారు. మేము హాస్టళ్లలో ఉంటూ, సెలవులకి ఇంటికి వచ్చినప్పుడు రోజూ సాయంత్రం బయట కూర్చుని పుస్తకం అవసరం లేకుండా అనేక కావ్యాలలో నుండీ పద్యాలు చదివి వినిపిస్తూ వ్యాఖ్యానిస్తూ ఉండేవారు. తర్వాత నేనే వారి పుస్తకాలు తీసుకుని చదవటానికి, ఎంతో కొంత తెలుగు, ఆపైన ఇంగ్లీషు నేర్చుకుని ఇప్పటికీ సాహిత్యంతో పరిచయం ఉంచుకోవటానికి పునాదులు అక్కడే పడ్డాయి. 

ఆ సాహిత్యాభిలాషను కొనసాగిస్తూ, సంసార సాగరంలో ఈదుతూ కూడా పద్య రచన వదలకుండా, ఇలా ఒక శతకం రాసి ప్రచురించటం వెనుక ఉన్న పట్టుదల, శ్రమ ఎంతగానో అభినందనీయం, మావంటి వారికి అనుసరణీయం. 

నాగేశ్వరరాజు గారు కొలిచిన సరస్వతీ దేవి ఎల్లకాలమూ వారిపై తన కరుణా కటాక్ష వీక్షణాలను ప్రసరింప చేస్తూ ఉండాలనేది వారి కుమారుడిగా, శిష్యుడిగా నా అభిలాష, ప్రార్థన. 

గవర్రాజు వేణుగోపాలకృష్ణంరాజు<br>
బెంగుళూరు<br>
10 డిసెంబర్ 2023<br>








