---
categories:
- musings
date: '2010-10-12T11:40:39+05:30'
title: 'Babaspeak: Renunciation'
---

Senior Bhakta, having got tired of the cryptic  preaching of IIMBaba, decided to explore the world for more worthy gurus and went to an ‘orientation session’ conducted by Sukhabodhananda Baba (SB Baba).

 SB Baba said – “Bhakta, letting go of the world and the desires attached to it is a good way of attaining peace with oneself.”

 Since it was an orientation session and he was not obliged to keep quiet in deference, Bhakta inquired “O Baba, why is it that all the godmen, who have already attained peace, are so eager to engage with more of this world?”

 “Bhakta, having attained a level of peace (that cannot be disturbed even by close contact with upcoming actresses in their birthday suits), we have come back into this world to spread awareness of its existence” clarified the SB Baba.

 Awestruck Bhakta had just enough strength left to stagger back into IIMbaba’s fold.

<!--
post-258
https://venugvgk.wordpress.com/2010/10/12/babaspeak-renunciation/
-->
