---
categories:
- musings
- life-as-it-happens
date: '2011-03-22T15:16:36+05:30'
title: En-counters of the Super-market kind
---

A visit to a library, any library, typically makes me very happy. The notion of standing surrounded by so many books on so many topics by so many authors is in itself very exciting. A super market also makes me happy for a similar reason.The mere knowledge of the existence of certain products fills me with a strange kind of satisfaction. The tuna fish packed in brine is a special favorite of mine though I have never been able to convince myself into buying it. Less forbidding things that I have tried include methi bread, a lollipop priced at 25 rupees, Saint grape juice (it tastes faintly like wine) and so on.

 The other reason I like supermarkets is the awesome quality of the human interactions: between shoppers (my favorite is when someone comes and asks me – “where do you guys keep detergent powders hidden?” with a touch of annoyance), between the shoppers and the shop assistants, between various assistants, the jumble of languages…after all, it’s a market! The indifference of some of the assistants, the poor English they speak, the righteous indignation of some of the shoppers…all these can get quite amusing. A Saturday morning visit to a supermarket near home in Bangalore has become a kind of pastime for me.

 One such Saturday morning, the supermarket was almost empty. I admired the fifteen varieties of breakfast breads for sometime and spent some more time gazing at all the ‘phorein’ vegetables like zuchini, multi\-colored capsicum, various grasses like rosemary, chinese cabbage and so on. And finally, as the point of time when missus would call from home asking ‘why the \*@\#$ is it taking you so long to buy a packet of milk’ was approaching, I reached the cash counter.

 There was a lady standing at the counter ready to pay the bill. Well dressed, well made up but slightly over the hill. Suddenly she started speaking very unkindly to the girl in the counter. The register was showing a bill for 10,000 rupees and the lady was getting angry. The girl in the counter, to her credit, pointed out the problem immediately: there was a banana stem priced at 9,000 rupees. She immediately called her supervisor over. The supervisor noticed that the banana stem was weighed (by the lady) at 1000 grams. It should have been sold at 9 rupees per piece but when you get it weighed, the scanner looks at the 1000 and multiplies it by the piece rate of 9 rupees. It was a series of small mistakes (the lady deciding to getting it weighed when it was to be bought per piece, the weighing counter girl not correcting the mistake and the girl at the cash register going with the weight instead of billing by piece) and was easy to spot and rectify.

 All this discussion took about 5 minutes and while it was going on, suddenly, the lady decided to up the ante. She started shouting that the girls in the counter do not know how to read numbers and that they do not even know how to read English letters. It was generally unfair but, okay, she was upset. Then she outdid herself by asking for the manager – she does not want that particular girl in the counter. And she started justifying her stand saying ‘people are busy, look how many people are having to wait because of such stupid mistakes’ and stuff. This was when she looked back at me and tried to include me in the ‘busy people’ waiting: I promptly stepped out of the sweep of her hand and looked away. Busy? you mean, ME??

 I felt like asking some questions: Assume the manager comes and she tells him not to put that girl in the counter. How is she going to ensure this happens? Is she going to come back at odd hours on sudden inspection visits? And if all the girls get ‘Fluent English’ training, will they continue to work as shop assistants? Especially if they start understanding all the things that we say about them? And some more questions: Why do we assume that people who are not smartly dressed are not sensitive to words like ‘stupid’? Would you call a fully grown adult ‘stupid’ in your mother tongue, however big the mistake s/he made? Okay, would you do the same in a regular vegetable market? They will hound you out, no matter how impeccable your English.

 All this drama was being enacted at one counter and everyone was engaged, having fun like I was. Including a smart looking young lady at the next counter. A middle aged, lower middle class looking guy just steps across in front of her and gets his one packet of bread billed. The lady suddenly wakes up. She has a ton of things to get billed. She gets upset. The guy does not even look at her. She gets more upset and starts mumbling. That guy looks at her, smiles and shows his single packet of bread. She gets outraged and starts talking about ‘common courtesies’ like asking her leave before jumping queue and all. In rather rude sounding English. She does not expect him to talk back. He does not look like the kind that can give it back in English. Unfortunately for her, he does give it back, and does it rather well. Both of them are upset now.

 I felt like asking more questions: what would she have done if he had asked her – said NO NO NO? Not likely. Then why is she bothered now? Reminds me of the “take the smaller piece of the cake when you get the first chance” kind of thought.

 Did I ask any of these questions? Did I even politely express my opinion, at least to show off my ‘balanced outlook’? Did I try to bring peace back to the universe? No way. Either of the women would have easily summoned enough energy to thrash me black and blue if I had. No chance.

 But, I have a plan. I am waiting another fifteen years. By that time, when I indulge in such perilious undertakings, the ladies will look at my awesome physique and thinning hair and will hopefully think – “okay, eccentric old man…let him live” and move on. Till then, mum’s the word.

<!--
post-366
https://venugvgk.wordpress.com/2011/03/22/en-counters-of-the-super-market-kind/
-->
