---
categories:
- musings
- poetry
date: '2011-05-27T10:16:07+05:30'
title: Sublime Sentiments/ Postmodernist Prattle/ Nonsense Notes
---

*(choose a title after you are done reading or feel free to substitute with one of your own)*

 I know most of you do not know most things about me. I am generally okay with it. But still, I was pained to discover the other day that a lot of you have never heard or even heard of my non\-prose literary efforts. While I was thinking of fishing out some of them from old notebooks and putting them here, a golden opportunity/random happenstance came my way.

 Krishnamoorthy, a classmate from B\-school and a good friend, sent me a poem (I use the term quite loosely, as you will figure out shortly). Since I was completely jobless, I wrote back. Thus started a long chain of emails that went on for about 5 hours during which we created the monumental (ahem!) work that I am now going to present here.  The ones on the right are mine.

 The longest response time (between emails – the time taken to ‘compose’) was about 25 minutes and the shortest was 10\. Stream\-of\-consciousness for you!!

 Disclaimers: No explanatory notes shall be provided. Use the postmodernist, preferably non\-structuralist approaches to make any sense. Feel free to write what you think. We reserve the right to make ‘poems’ out of comments and throw them back at you.



| A scoop of vanilla ice cream Sitting pretty on a cone Melts and drips and drips With no one around to taste On a bright Saturday afternoon I cycle eight beautiful kilometers Only to discover that The ice candy man was long dead | a dollop of dull yellow poop floating leisurely under the dome twists, turns,rots and stinks with no one around to flush it down On a boring Sunday morning I scrub the entire house only to discover that the stink comes from elsewhere |
| --- | --- |
| Standing on a depressingly clean balcony I remembered with a strange fondness The pigeon droppings in various degrees of decay A bit worried, I wondered If I was in the right house Only to discover that It was just another way of Seeing the same old shit | In the face of cleanlinesssee the shit underneath under the familiar shit lies an unknown ugly world when not working becomes a way of working harder when the pain is self\-inflicted why even think about pleasure? |
| To have come thus far To have climbed many a ladder And reach a point Where Not working becomes a way of working harder. If this is not progress then what is? Time for a pay hike! | progress regress digress climb up down run away begin end busy idle work leisure pleasure pain think do oppress impress enlighten kill humiliate love like hate ignore destroy create color mold anger jealousy pity piety god dog devil woman high flat low dim bright dark stupid trim chop the ladders break the steps bomb the world kill yourself |
| When you can bomb the world And kill yourself Why wait for the lights to go down And angels to come and wish you bye? Now is the time Now is the time. But wait.. What about that report submission? Ain’t there a deadline for Monday Go ahead Complete that one last one And die in peace After all dying can wait! | what does peace matter when life does not; or should it? if dying can wait and life is waiting what matters time? |
| Piecemeal dying Seems to be in fashion these days Bit by bit Bit by bit Live life to the maximum they say! Over the giant wheel On the very top Sits a young girl Gripping the safety bar tight And when the giant wheel spins The poor girl screams in fright Or may be fun Who knows? | if she knew it was fun or fright in precise detail and analysed and understood, will she ever get on the wheel again? creeping inch by inch to death – that is politely called life push on for now the time to try claw your way back will come soon enough. |
| Creeping inch by inch to death Politely called life? Is this frustration or A plain oversupply of a certain currency called time? | looking beyond the facade? how lovely! do you wish to dig and tunnel in to no man’s land? in to sinew, heart and mind? how noble! any truth in there? one or many, right or wrong am I gay or straight? sound, picture or the thought build it up or break it apart? is it my over anxious mother? or is it simply about power? |
| Got no doubts now whatsoever; It is time, time and loads of more free time That manifests itself into these lines May the jobless be blessed and their tribe grow! It might be  of interest to know that The overanxious mother is waiting outside With a jar of pickles One to tease each of your tease buds | butler botler derrida eagleton eco fish you had your pick! there was conrad forster pound and proust if old was your gold in a different vintage we offered keats peacock emerson pater and wilde alas! you choose camus esslin beckett and pinter or is it simply all pitter patter? |
| In the three hours that I stood in the bus stand Several buses came and left I got in one that caught my fancy Not a clue where the bus goes But I am told The driver is a  sane person | there is a train i want to get on I know where its headed where it starts and how long it takes the number of coaches I counted and the width of seats, measured I need to hurry to talk to the driver bye bye for the day. |

<!--
post-372
https://venugvgk.wordpress.com/2011/05/27/sublime-sentiments-postmodernist-prattle-nonsense-notes/
-->
