---
title: Session 2 - Exploring Quadratic Curves - Questions
date: 2026-09-09
page-layout: article
publish: false
format:
  html:
    toc: true
    code-fold: true
    html-math-method: katex
    fig-align: center
    fig-width: 7
    fig-height: 5
jupyter: python3
execute:
  warning: false
---

## Exploring $y=ax^2$

1. Make a table of values for $y=x^2$, using positive, negative, and zero values of $x$. What do you notice? Is the graph symmetric? If so, about which axis? What is the shape of the graph? What is the lowest/highest point?

2. Plot $y=2x^2$ and $y=0.5x^2$ on the same graph. What do you notice about the shape of the graphs? Which one is wider? Which one is narrower? What is the lowest/highest point of each graph?

3. Plot $y=-x^2$ and $y=-2x^2$ on the same graph. What do you notice about the shape of the graphs? What is the lowest/highest point of each graph? 

4. Based on your observations, what is the effect of the coefficient of $x^2$ on the shape of the graph? What is the effect of a negative coefficient?

## Exploring $y=ax^2+c$

5. What happens when you plot $y=x^2+2$ and $y=x^2-3$? What do you notice about the shape of the graphs? What is the lowest/highest point of each graph? Do these graphs intersect the $y$-axis? If so, where? How does the graph of $y=x^2$ change when 2 is added or 3 is subtracted? Which way does it shift?

6. Plot the graphs of $y=2x^2$, $y=2x^2+4$, $y=2x^2-4$, $y=-2x^2+4$, $y=-2x^2-4$. What do you notice about the shape of the graphs? What is the lowest/highest point of each graph? Do these graphs intersect the $x$-axis and $y$-axis? If so, where?

7. Based on your observations, what is the effect of the coefficient of $x^2$ on the shape of the graph? What is the effect of a negative coefficient? What is the effect of the constant term $c$ on the shape of the graph?

## Exploring $y=ax^2+bx$

8. Plot the graphs of $y=x^2+2x$ and $y=x^2-2x$, What happens to the graph of $y=x^2$ when 2x is added or subtracted? Does the shape of the graph change? Does the lowest/highest point change? Does the point of intersection of the axis change? 

9. Based on your observations, what is the effect of the coefficient of $x$ on the shape of the graph? What is the effect of a negative coefficient?

## Exploring $y=ax^2+bx+c$

10. Plot the graphs of $y=x^2+2x+2$, $y=x^2+2x-2$. What happens to the graph of $y=x^2+2x$ when 2 is added or subtracted? Does the shape of the graph change? Does the lowest/highest point change? Does the point of intersection of the axis change?

## Summarising the observations

11. Based on your observations, what is the effect of the coefficient of $x^2$ on the shape of the graph? What is the effect of a negative coefficient? What is the effect of the coefficient of $x$ on the shape of the graph? What is the effect of a negative coefficient? What is the effect of the constant term $c$ on the shape of the graph?



