---
categories:
- musings
date: '2011-11-02T12:59:17+05:30'
title: Meaning of Life
---

IIMBaba was reading a book review online and came across a quote at the beginning of [this](http://www.nybooks.com/articles/archives/2011/aug/18/how-google-dominates-us/?pagination=false)  review: Tweets Alain de Botton, philosopher, author, and now online aphorist: “The logical conclusion of our relationship to computers: expectantly to type “what is the meaning ofmy life” into Google”

 And sent it on the mailing list of his Bhaktas, to provoke thought.

   Senior Bhakta replies to all  – “just now typed it in Google. There are 48,400,000 results, offered up in 0\.11 seconds. What to pick and read?”

   The very recently joined junior Bhakta, nervously checking mail on his blackberry does not want to be outdone. He writes – “I typed ‘what is the meaning of my life’ in my Google window and got 118,000,000 results in 0\.24 seconds. Does that mean my life is longer and more meaningful than yours?”

   He then went on to publish on his blog that night: “according to Google, people with 2 years of post\-MBA experience have nearly double the meaning in their lives compared to those that have more than 5 years of post\-MBA experience”.

   Last heard, he was turning it in to a peer reviewed paper for the international webinar on “Meaningful Work and Life”.

<!--
post-409
https://venugvgk.wordpress.com/2011/11/02/meaning-of-life/
-->
