---
categories:
- poetry
- telugu
- translation
date: '2018-01-22T08:15:25+05:30'
title: నేనెందుకు హోం వర్కు చెయ్యలేదంటే…
---

కెన్ నెస్బిట్ అమెరికన్ పిల్లల కవి. ఆయన పిల్లల కోసం హాస్య కవిత్వం రాస్తాడు. పిల్లల ఊహల్లాగే ఈయన కవితలు కూడా నమ్మశక్యం కాని సంఘటనలు, అద్భుతమైన సన్నివేశాలతో మొదలయ్యి, చివరికి ఈ లోకంలోకి వస్తాయి. ఈయన కవితల్లో పిల్లలకి బాగా పరిచయమయిన సందర్భాలు ఎంచుకుంటాడు. చాలా కవితల్లో స్కూలు, రూల్సు, పెద్దవాళ్ళని అపహాస్యం చేస్తాడు.

 All my great excuses అనే కవితకి అనువాదం ఇది.

 నేనెందుకు హోం వర్కు చెయ్యలేదంటే…

 నేను హోం వర్కు చేద్దామనే అనుకున్నా,<br>
 కానీ నా పెన్నులో ఇంకు అయిపోయింది.<br>
 మా పెంపుడు ఎలుక నా పుస్తకం తినేసింది<br>
 మా ఇంట్లోనేమో కరెంటు అసలే పోయింది

 నా హోం వర్కు పుస్తకం చెయ్యిజారి<br>
 పొయ్యి మీద రసంలో పడి కరిగిపోయింది<br>
 నేను వేరే పనిలో బిజీగా ఉన్నప్పుడు<br>
 మా చెల్లి దాన్ని మురిక్కాలవలో పడేసింది

 మా అమ్మ పనితొందరలో కంగారులో<br>
 నా హోం వర్కు శుభ్రంగా ఉతికి ఆరేసింది.<br>
 విమానం ఒకటి మా ఇంటిమీద కూలిపడి<br>
 నా హోం వర్కు ఆ మంటల్లో కాలిపోయింది

 సుడిగాలికి నా నోట్సు కొట్టుకుపోయాయి.<br>
 మా ఊళ్ళో అగ్నిపర్వతాలు బద్దలయ్యాయి<br>
 మాయల మరాఠీ ముఠా చేతులో<br>
 అందమైన నా పుస్తకాలు బందీలయ్యాయి.

 నా మీద ఒక షార్కు దాడిచేసింది<br>
 వేరే గ్రహం వాళ్లు నన్ను ఎత్తుకుపోయారు<br>
 బందిపోట్లు నా హోం వర్కు దొంగిలించి<br>
 తిరిగివ్వమంటే కుదరదంటున్నారు

 పని తప్పించుకోటానికి మంచి సాకుకోసం<br>
 ఇంత కష్టపడి నేను వెతుకుతున్నానా,<br>
 చూడండి, మా టీచరమ్మ “ఒరే బుజ్జీ, దీనికన్నా<br>
 హోం వర్కు తేలికేమోరా” అని వెటకరించిది.

 Kenn Nesbitt is an american children’s poet. He writes humourous poetry for children. His poems often include outrageous happenings before concluding on a realistic note, just like in the imagination of children. Many of his poems are set in contexts familiar to children and make fun of school, rules and grownups.

 Here is the poem “All my great excuses”

 I started on my homework<br>
 but my pen ran out of ink.<br>
 My hamster ate my homework.<br>
 My computer’s on the blink.

 I accidentally dropped it<br>
 in the soup my mom was cooking.<br>
 My brother flushed it down the toilet<br>
 when I wasn’t looking.

 My mother ran my homework<br>
 through the washer and the dryer.<br>
 An airplane crashed into our house.<br>
 My homework caught on fire.

 Tornadoes blew my notes away.<br>
 Volcanoes struck our town.<br>
 My notes were taken hostage<br>
 by an evil killer clown.

 Some aliens abducted me.<br>
 I had a shark attack.<br>
 A pirate swiped my homework<br>
 and refused to give it back.

 I worked on these excuses<br>
 so darned long my teacher said,<br>
 “I think you’ll find it’s easier<br>
 to do the work instead.”

<!--
post-594
https://venugvgk.wordpress.com/2018/01/22/%e0%b0%a8%e0%b1%87%e0%b0%a8%e0%b1%86%e0%b0%82%e0%b0%a6%e0%b1%81%e0%b0%95%e0%b1%81-%e0%b0%b9%e0%b1%8b%e0%b0%82-%e0%b0%b5%e0%b0%b0%e0%b1%8d%e0%b0%95%e0%b1%81-%e0%b0%9a%e0%b1%86%e0%b0%af%e0%b1%8d/
-->
