---
categories:
- musings
date: '2010-09-21T20:00:29+05:30'
title: 'Babaspeak: It’s a game of chess'
---

IIMBaba’s discourse that day was about ‘karmanyevaadhikaaraste….’ from Bhagavadgita, where Lord Srikrishna said things to the effect that you have an obligation to perform your duty but you should not be driven by the expectation of the returns. Naturally, most of the Bhakta’s were having significant difficulties with this apparent ‘counter\-intuitive’ line of thought.

 Senior Bhakta, in the warm glow of post\-discussion resonance, was holding forth: “Life is anyway such a gamble and so full of uncertainity…” and so on.

 Junior Baba interjected: “Life is more like a game of chess”

 Sr. Bhakta, momentarily taken aback, looked thoughtful, shook his head a couple of times, apparantly at the dawn of a new understanding, and tried a comeback: “yeah, I see what you mean…there is definitely an element of skill and thought…”.

 Very uncharacteristically for a Baba, Jr. Baba cut in again and explained: “When you gamble, you typically trust in chance and you know that it could go either way. When you lose, you can blame your luck. At any point of time, you know how far ahead or behind you are. Technically, you can choose to stop playing anytime. Hopefully, you quit while you are ahead of the game.

 Now, think of a game of chess. You start the game thinking that you have the skill to win. You think long and hard building the foundations for a win. You invest effort, hope and all for some time. Then the setbacks start, with a significant lag, allowing you enough time to kick yourself for all the mistakes you have been making. There is no going back and there is no knowing whether you are winning or losing. By the time you realise you are definitely losing, it’s usually too late to do anything about it”

 Bhaktas were so engrossed in this vision that there was no comment when Jr. Baba added softly, as if to himself: “And eventually, lose you shall, however inconceivable it looks right now”.

<!--
post-194
https://venugvgk.wordpress.com/2010/09/21/babaspeak-its-a-game-of-chess/
-->
