---
categories:
- musings
date: '2010-04-14T16:30:35+05:30'
title: Here we go!
---

This is my first blog post… (did you know there is a yet\-to\-be\-named disease, the main symptom of which is stating\-the\-obvious?? There is.)

 I am personally very happy that this humble beginning is taking place in the right setting…on a restaurant table after a very satisfying beer and a biryani.

 By the way, did you ever smell out a restaurant??

 I am in Bangalore on a life or death mission and the various things have been slowly falling in place. Four days in to the mission, most things are taken care of and then the final piece slowly slid in to place. In the associated excitement/relief, i realized only at 3 pm that i hadn’t had any meal. And i was in the unfamiliar environs of Bangalore on the 100 feet road in Indiranagar. I kept walking in the hope that there will be something on the road somewhere.

 Suddenly there was this whiff of spicy cooking…the only thing visible in the distance was a Cafe Coffee day which is like the farthest thing on your mind when you are looking for a good solid lunch…but still, my nose urged me on…i kept sniffing and walking…and sniffing and walking..and there it was…an “ANNAACHI, Truly chettinad” place hidden high above the coffee day. While slowly climbing the stairs I called the missus and told her of my awesome achievement. she was kind enough to say “very good, go eat now”…like she does with my kid. You know, she is had experience.

 There was this sign on the door to tempt people like me “DLF IPL OFFER…ORDER TWO PINT BOTTLES OF BEER AND GET THE THIRD FREE, FREE, FREE”. I look at the menu and there is the scam in the open. A full bottle (MRP Rs.80\) at Rs. 130 and a pint bottle (MRP Rs.41\) priced at Rs. 100\. All that the guy is offering me is the convenience of having one and half beer instead of having to order two beers. The price remains the same. Given the heat (of the moment and outside), i consider this favorably compared to  the offer the other restaurant gave (one beer free for two – you kind of convince yourself in to having all the three) and go for it. Note for the missus: It was REALLY HOT, you know!!

 Anyway, the deed is done…they are closing down for the afternoon and i am going to the Coffee day downstairs for a nice hot coffee…

<!--
post-3
https://venugvgk.wordpress.com/2010/04/14/here-we-go/
-->
