---
categories:
- musings
date: '2010-06-09T12:55:44+05:30'
title: A Summer Shower
---

The other day we went to visit an uncle in Dwaraka. He lives in a well maintained housing society\- open lawn inside, silent generators, ground floor dedicated to parking and the works. The lawn is located in the center of the society. The seven towers, each with seven stories, are arranged around the lawn so that each tower has a view of the lawn.

 The weather that evening was very nice. Dark clouds were gathering from one side. The sun was still shining on the other side. The buildings were very brightly lit against the dark background of clouds and were looking brand new. The greenery around had taken different hues due to the contrasting lighting and background. It looked like an indoor setting for a movie about summer showers. The breeze was cool and rain was in the air.

 After some time, I was getting tired of the view. Just then I noticed a small girl on the opposite balcony. She had a big mushroom of hair. She was dancing and the mushroom was flaring. It started to drizzle and a big brother came out with a multi\-colored umbrella. Soon the umbrella started twirling in to a rainbow.

 Slowly I started to notice more and more people on the balconies. Not all of them were as visible as the girl and the umbrella. Not too many of them were carrying rainbows. There was this well lit balcony and till I noticed the lone guy sitting in the shadows, I thought it was empty. He looked old to me. On a top floor balcony two young men and a woman were sitting around in cane chairs, having tea. A kurta clad middle aged paunch was rocking on a third floor. A shapely, track suited girl was looking down from a seventh floor window. A small girl was jumping in to every puddle in the parking lot and her youngish parents were walking behind her leisurely. The lady in the adjacent fifth floor balcony had been on the phone all the while, unmindful of the view or the weather. In a half\-lit kitchen, a maid was cooking away.

 The rain started to beat down in a steady drone. Most people were moving back indoors and the light was fading in to darkness

 For some strange reason, I suddenly thought of a zoo.

<!--
post-94
https://venugvgk.wordpress.com/2010/06/09/a-summer-shower/
-->
