---
categories:
- books
date: '2011-03-21T01:01:38+05:30'
title: 'Dean: On The Road'
---

Just about finished reading ***On The Road***. I dig Dean Moriatry and his quest for IT. I dig his digging the kind of things he digs. I dig Sal digging the same things, a little less deep. I might simply sniff at or, at the best, scratch at those. To each, his depth and shallowness. To each, his own seeking and fleeing. To each, his freedom and bondage to love or hate.

 I see Dean going on quest after quest. Each longer than the last one. Each with a new set of acolytes. Each ending, not in heaven or hell or IT or beyond, but in the middle of nowhere. And the next one beginning and ending. Will any one of them ever end before it begins? Unlikely with Dean. He will then become one of us. No, we can’t have that.

 Let me get to the point. It’s this absolutely wonderful quote:

 “Now you just dig them in front. They have worries, they’re thinking about where to sleep tonight, how much money for gas, the weather, how they’ll get there – and all the time they’ll get there anyway. You see. But they need to worry and betray time with urgencies false and otherwise, purely anxious and whiny, their souls really won’t be at peace unless they can latch on to an established and proven worry and having once found it they assume facial expressions to fit and go with it, which is, you see, unhappiness, and all the time it all flies by them and they know it and that *too* worries them no end. Listen! Listen!……Man, you dig all this.”

 I worry that these days I *might* have started worrying a *little – wee – bit less* about a lot of things. You have a nice day!

<!--
post-362
https://venugvgk.wordpress.com/2011/03/21/dean-on-the-road/
-->
