---
categories:
- life-as-it-happens
date: '2010-04-27T00:05:28+05:30'
title: The Quest for an opener
---

I love multipurpose tools. They are like, so multi purpose. And so handy. And, you know, some times, so discreet.

 For example, think of that nice nail cutter I had. It had a blade with a small groove (groovy, huh?) that could easily slip the cap off a nice, cold beer bottle. It was always handy and, you know, never any quizzical looks from aged relatives.

 Ever since I bought this dedicated bottle opener (wine and beer), it’s always been misplaced. May be missus took it along today to open the bottle of flavored milk for the kid in the break time…can you beat that??

 And these door jambs are also useless. You press a flimsy bottle cap in the jamb trying to open it and the door paint starts flaking off. Now, the wood is getting splintered. These house owners are a bunch of thieves, I tell you. No single decent door jamb. I sooo miss my student days and the hostels, at least they had respectable iron doors.

 None of the handles of the sturdy (sir, it will last a life time…) kitchen appliances worth hundreds of rupees each is up to the task. That stupid tea strainer handle actually bent out of shape….BENT OUT OF SHAPE…..God…!! let me fix that up quick.

 And this tooth ache is killing me. At thirty, JUST THIRTY, my teeth are giving up on me. What good is a bunch of teeth if you can’t open a bloody bottle cap, even after getting chipped in the process, I ask you? I will sue that stupid dentist guy. He told me last time that my teeth are in ‘splendid condition’…splendid, \#$%\&!!

 Hmmmm…gulp..gulp…gulp…I looooovvvvvve these big house keys. They might be a bit of a pain to carry around in the pockets of bought\-before\-the\-expansion jeans but when it comes to bottle caps, they work magic.

 After a day’s hard work (buying toys for kids IS a cerebrally demanding task), don’t you think a guy is entitled to a couple of sandwiches and a beer? Anyways, see you tomorrow.

<!--
post-63
https://venugvgk.wordpress.com/2010/04/27/the-quest-for-an-opener/
-->
