---
categories:
- life-as-it-happens
date: '2018-10-26T21:00:38+05:30'
title: Children, these children!
---

I was on a trip with a bunch of kids. About a couple of hours into the journey, kids were getting bored so we start asking riddles and telling jokes.<br>
One of my fellow adults asks the following:<br>
A man is going in his car. He hits someone, gets down and realises it’s his son! Both of them rush to the hospital. The injury is serious and an emergency surgery is scheduled. The surgeon walks into the room and says, “my god, this is my son!!”<br>
How is this possible?

 We were waiting for the kids to realise that it appears impossible at first because they automatically assume the surgeon is male. We expect them to then reason and realise the surgeon could be a woman and so the boy’s mother. We were waiting for a neat trick  to unfold, showing up the children’s biases.<br>
Instead, one of the kids says, “it’s a gay couple.”<br>
Now it’s our turn to wonder what biases we the adults are operating from.<br>
These kids, I am telling you!! ☺️<br>

<!--
post-732
https://venugvgk.wordpress.com/2018/10/26/children-these-children/
-->
