---
categories:
- poetry
- translation
- telugu
date: '2021-07-06T21:43:57+05:30'
title: I Don’t Want to Be a Spice Store – translation
---

I Don’t Want to Be a Spice Store<br>
By Christian Wiman

 Go to the podcast in the link below to listen to the poet talking about the poem. Intersting stuff!

 <https://poetryforall.fireside.fm/21>

 ఇంకెక్కడా దొరకని ప్రత్యేక దినుసుల దుకాణంలా<br>
ఉండాలని నాకు ఆశలేదు<br>
చేత్తో చేసిన చందనపు సువాసనల సబ్బులు,<br>
ప్రపంచపు అంచులనుండీ పట్టుకొచ్చిన వెన్న,<br>
ముప్ఫైరకాల మత్తెక్కించే మద్యాలు,<br>
అందరికీ అందుబాటులో ఉంచాలని నాకు లేదు

 దివ్యత్వంలో ఊరబెట్టినట్టుండే పుస్తకశాలలతో సహా<br>
ఇక్కడ దుకాణాలు మధ్యాహ్నం వరకూ మూతపడే ఉంటాయి<br>
నేను రాత్రీ పగలూ ఎప్పుడూ తెరిచి ఉండే దుకాణం అవుతాను<br>
అవసరమైన సామాను తప్ప ఇంకేమీ ఉండదు నాలో<br>
పొయ్యిలో మంట రాజేసేందుకు ఒకటి<br>
అవసరమైతే మంటల్ని ఆర్పేయ్యటానికి ఒకటి<br>
సామాన్లన్నీ చల్లగా ఉండిపోయే స్థలం ఒకటి<br>
అన్నీ తియ్యటివి ఉండేవి ఒకటి<br>
చెవులు గట్టిగా మూసేసుకోవటానికి,<br>
కళ్ళకి ఉపశమనం కలిగించటానికి<br>
అవకాశాలు నాలో కల్పించుకుని ఉంచుకోవాలి<br>
ఇక బాగుచెయ్యలేమేమో అనుకునే చిరుగులూ, పగుళ్ళని<br>
అతికించి బాగుచేసే బలమైన జిగురు,<br>
రోజువారీ ఉత్పాతాలకి విషరహితమైన విరుగుళ్లు.<br>
మిలమిలా కాంతితో మెరిసిపోతూ,<br>
చిన్నప్పుడు నాకు లేని ఓపికతో<br>
మా నాన్నకి తెరిచి ఉండి కనిపించాలి.<br>
చివరి ప్రయత్నంగా తానొక్కడే<br>
క్రిస్మస్ ఉదయాన బహుమతుల కోసం<br>
తిరిగేటప్పుడు తెరిచి ఉండి కనిపించాలి.<br>
“విశ్వానికి వెలుగు”నిచ్చే పెన్ లైట్,<br>
ఊగిసలాడే దిక్సూచి,<br>
ఎటు పడతాయో తెలీని పాచికలు<br>
తెల్లవారుజామున నాలుగ్గంటలకి లోపలి ఖాళీతనంతో<br>
గునుస్తూ మెల్లగా పాడుతూ తెరిచే ఉండాలి.<br>
నా తలుపులు తెరిచినప్పుడు చిన్న గంటలు మోగాలి.<br>
నాకొక తలుపు ఉండాలి.

 I don’t want to be a spice store.<br>
I don’t want to carry handcrafted Marseille soap,<br>
or tsampa and yak butter,<br>
or nine thousand varieties of wine.<br>
Half the shops here don’t open till noon<br>
and even the bookstore’s brined in charm.<br>
I want to be the one store that’s open all night<br>
and has nothing but necessities.<br>
Something to get a fire going<br>
and something to put one out.<br>
A place where things stay frozen<br>
and a place where they are sweet.<br>
I want to hold within myself the possibility<br>
of plugging one’s ears and easing one’s eyes;<br>
superglue for ruptures that are,<br>
one would have thought, irreparable,<br>
a whole bevy of non\-toxic solutions<br>
for everyday disasters. I want to wait<br>
brightly lit and with the patience<br>
I never had as a child<br>
for my father to find me open<br>
on Christmas morning in his last\-ditch, lone\-wolf drive<br>
for gifts. “Light of the World” penlight,<br>
bobblehead compass, fuzzy dice.<br>
I want to hum just a little with my own emptiness<br>
at 4 a.m. To have little bells above my door.<br>
To have a door.

 Christian Wiman is the Clement\-Muehl Professor of Communication Arts at Yale Divinity School, the former editor of Poetry magazine, and the author, editor, and translator of multiple books. He has won countless awards for his poetry and also has extraordinary books of prose, including My Bright Abyss and He Held Radical Light. This poem “I Don’t Want to be a Spice Store” is from his latest book of poetry, Survival is a Style.

<!--
post-777
https://venugvgk.wordpress.com/2021/07/06/i-dont-want-to-be-a-spice-store-translation/
-->
