---
categories:
- musings
date: '2016-07-14T15:56:59+05:30'
title: How logic can help keep friendships
---

​Here are a couple of ideas that have helped me stay logically correct and keep my friendships longer.

 Sometimes, people we think of as friends do things that greatly upset us. More often than not, we are hurt and start thinking of the said friend’s intentions. Given enough time, we end up questioning our judgements about the friend, his/her overall character and tend to reevaluate his/her past behaviour through a more negative lense. Very soon, we are no longer friends and sorry about the fact that we are no longer friends.

 Sometimes, WE do things that greatly upset our friends. When we become aware of the fact that the friend is upset, we set out to explain – “please understand WHY I did this”. The friend asks – “why would YOU do something like this?”

 Note the difference in focus – we find it is easier to take into account the impact of situations, circumstances and external factors when explaining our behaviour but find it difficult to account for these factors to explain the other person’s behaviour. This is a cognitive bias called “fundamental attribution error”, also known as the correspondence bias or attribution effect. This bias, as defined on Wikipedia, is the tendency of people to place undue emphasis on the character or intentions of people, rather than external factors when explaining another person’s behaviour in a given situation. This contrasts with interpretating one’s own behavior, where situational factors are more easily recognized and can be taken into account.

 When we recognise that it is common for us to blame character or intention for other’s actions and ignore situational factors, it becomes that much more easy to  stop the negative cycle of questions, be more open, have a conversation, and clear up things.

 Hanlon’s razor is a less tedious and more fun way of saying nearly the same as the above. A version of it goes – “Never assume malice when stupidity will suffice”, or “Never attribute to malice that which is adequately explained by carelessness”.

 Both of these ideas help us broaden our focus when we are dealing with people and allow us to take more factors into account to explain or enquire about their behaviour.  With the right mindset and the right set of questions, we can understand each other more and remain friends much longer.

<!--
post-560
https://venugvgk.wordpress.com/2016/07/14/how-logic-can-help-keep-friendships/
-->
