---
categories:
- musings
date: '2010-08-03T13:25:40+05:30'
title: Does it matter?
---

Single column news on the first page of The Hindu today:

 [“Deadlock over prices issue ends”](http://www.thehindu.com/news/national/article547649.ece)

 According to the report, a resolution is will be moved in both the houses expressing concern over inflationary pressure on the economy and calling up on the Centre to take steps to reduce its adverse impact on common man. And all these people have been fighting over the wording of the resolution. A discussion on this resolution is scheduled for today.

 I was already wondering why a week of collective energy has been wasted on this thing. “another report on page 12” revealed that perhaps this is the first time that such a resolution will be adopted on a subject like inflation. I thought may be this is a big thing and may be the week was not completely wasted.

 Then came the killer – “In recent memory resolutions were adopted on Kashmir being an integral part of India, on the 2002 Gujarat riots, and on the occupation of Iraq by the US”.

 Does it matter?

 And come to think of it again, if they had not wasted that one week on this issue, what else could they have done? Pick a more appropriate issue to waste time on?

<!--
post-127
https://venugvgk.wordpress.com/2010/08/03/does-it-matter/
-->
