---
categories:
- musings
date: '2011-01-20T15:06:32+05:30'
title: 'Babaspeak: Happiness, Freedom and Peace'
---

One fine morning, Senior Bhakta, checking his mail while in IIMBaba’s presence, received this ‘Thought for the Day’ in his email inbox.

 **“There is a wonderful mythical law of nature that the three things we crave most in life — happiness, freedom, and peace of mind — are always attained by giving them to someone else”**

    After reading the quote, senior Bhakta erupted indignantly:

 “This is getting out of hand day by day…didn’t they say sometime back that happiness, freedom and peace of mind are to be found within and it’s an individual’s nature that determines whether he has them or not?? So, if I don’t have any of these I am the only person responsible…Now, if these are to be found within you, how can I ‘give’ them to you? I know from the little experience I have that it is impossible to ‘give’ peace of mind to someone. That someone has to find his own peace of mind.

 This way, I am responsible for my unhappiness and that is also because I have not given happiness to you. How sensible is that?” And so on…

 When he was sufficiently calmed down, IIMbaba asked gently, “Bhakta, is it just possible that there is no real meaning attached to either of the two points of view ?”

 When Bhakta was suitably startled and started to pay attention, he continued, “don’t you think there is something suspicious about the way life is made to sound like a quest, a means to some end? Critically examine the value you attach to concepts like freedom and happiness. Where does this value come from? Is it not some form of conditioning? Now, knowing your elders, your contemporaries and yourself like you do, is it just possible that we all have got it completely wrong?”

 Bhakta nodded sagely and the discussion continued.

 He was later overheard, sounding very pleased, saying: “it is a good approach. When the solutions or the lack of any baffles you, you should look at redefining the problem. I guess that’s what they teach you at the Babaschool also”

<!--
post-318
https://venugvgk.wordpress.com/2011/01/20/babaspeak-happiness-freedom-and-peace/
-->
