---
title: write code and show output
format: html
---

‘No one can craft a jutti like I do’

జుత్తీ చేయటంలో నన్ను మించినవాళ్ళు లేరు 

In the village of Rupana, veteran shoemaker Hans Raj is the only artisan who still makes leather juttis by hand, a craft requiring great skill and precision, and traditionally practised by Dalit families from Punjab

రూపానా గ్రామంలో చెప్పులు కుట్టే వృత్తిలో చేయి తిరిగిన హన్స్ రాజ్ ఒక్కరికే ఇంకా చేతితో తోలు జుత్తీలు కుట్టే పనితనం ఉంది. సాంప్రదాయికంగా పంజాబులో దళిత కుటుంబాలు చేస్తూ ఉన్న ఈ చేతిపని చేయటానికి చాలా నేర్పరితనము, సున్నితమైన ఖచ్చితత్వమూ కావాలి. 

“Lai de ve jutti mainu,
Muktsari kadai wali,
Pairan wich mere channa,
jachugi payi bahali’’

"లాయ్ దే వే జుత్తీ మేనూ,
ముక్త్ సరీ కడాయీ వాలీ 
పైరన్ విచ్ మేరే ఛన్నా
జచూగీ పాయి బహాలీ"


“Buy me a jutti ,
the one with Muktsar’s embroidery,
In my feet, oh my beloved, it will look amazing.”

"ముక్తసర్ చేతికుట్టు పని చేసిన 
జుత్తీ నాకు కొనిస్తావా, ప్రియా 
అందమైన నా పాదాలకి అవి 
ఎంత చక్కగా అమరుతాయో కదా"

Hans Raj tightens his grip on the coarse cotton thread. Using a sharp steel needle to guide it, the veteran shoemaker pierces the tough leather, skillfully moving the needle in and out roughly 400 times to hand-stitch a pair of Punjabi juttis (closed shoes). As he does so, his heavy sighs followed by ‘hmms’ punctuate the silence.

తన చేతిలో ఉన్న బిరుసైన నూలు దారాన్ని ఇంకొంచెం బిగించి పట్టుకున్నారు హన్స్ రాజ్. మొనదేరిన ఉక్కు  సూది సహాయంతో ఆ దారాన్ని గట్టి తోలులోకి దించి, ఎంతో చాకచక్యంగా సూదిని కదిలిస్తూ, దగ్గర దగ్గర నాలుగు వందల కుట్లు వేస్తేనే ఒక జత పంజాబీ జుత్తీ (మూసిఉండే ఒకరకం చెప్పులు) తయారవుతాయి. ఆయన పని చేస్తున్నప్పుడు బరువైన నిట్టూర్పులు, 'హుమ్మ్' అనే శబ్దాలు తప్ప అంతా నిశ్శబ్దంగా ఉంటుంది. 

In the village of Rupana in Sri Muktsar Sahib district of Punjab, Hans Raj is the only artisan who makes these juttis the traditional way.

పంజాబులోని శ్రీ ముక్తసర్ సాహిబ్ జిల్లాలో, హన్స్ రాజ్ మాత్రమే ఈ జుత్తీలని సాంప్రదాయక పద్ధతిలో తయారుచేయగల ఏకైక చేతిపనివాడు..

“Most people are unaware how a Punjabi jutti is made and who crafts it. There is a common misconception that machines make it. But from preparation to stitching, everything is done by hand,” says the 63-year-old artisan who has been crafting juttis for nearly half a century now.  “Wherever you go, Muktsar, Malout, Gidderbaha or Patiala, no one can meticulously craft a jutti like I do,” Hans Raj says matter-of-factly.

"చాలా మందికి పంజాబీ జుత్తీ ఎలా, ఎవరు తయారు చేస్తారో తెలియదు. అందరూ వీటిని యంత్రాలు చేస్తాయని అనుకుంటారు. కానీ, ఇవి మొదటి నుంచీ చివరివరకూ, పూర్తిగా చేతితోనే తయారు అవుతాయి," అంటారు హన్స్ రాజ్. అరవై మూడు సంవత్సరాల ఆయన, దాదాపు అర్థ శతాబ్దకాలంగా ఈ జుత్తీలను తయారు చేస్తున్నారు. "మీరు ఎక్కడికైనా వెళ్ళండి, ముక్తసర్, మాలౌత్, గిద్దర్బహా, కావాలంటే పటియాలా, నా అంత శ్రద్ధగా జుత్తీలు చేసేవాళ్ళు మీకు దొరకరు," అని చాలా మామూలుగా అంటారు హన్స్ రాజ్.  

Every day, starting at 7 a.m., he sits on a cotton mattress on the floor near the entrance of his rented workshop, part of the walls covered with a collection of Punjabi juttis for both men and women. A pair is priced between Rs. 400 to Rs. 1,600, and he says he can earn about Rs. 10,000 a month from this livelihood.

ప్రతి రోజూ ఉదయం ఏడు గంటల నుంచీ ఆయన తన అద్దె దుకాణం ద్వారం దగ్గర ఒక దూది పరుపు మీద కూర్చుని ఉంటారు. 
ఆ దుకాణం గోడలలో కొంత భాగం జుత్తీలతో నిండి ఉంటాయి. అందులో మగవాళ్ళ కోసం చేసినవి, ఆడవాళ్ళ కోసం చేసినవి కూడా ఉంటాయి.  ఒక జత ఖరీదు 400 రూపాయల నుండీ 1600 రూపాయలకు ఉంటుంది. ఈ వృత్తి నుంచీ తనకు నెలకు 10,000 రూపాయల వరకూ సంపాదన 
ఉంటుందని చెప్పారు. 

Left: Hans Raj’s rented workshop where he hand stitches and crafts leather juttis. Right: Inside the workshop, parts of the walls are covered with juttis he has made

ఎడమ: హన్స్ రాజ్ చేతితో కుట్టి, తోలు జుత్తీలు తయారు చేసే అద్దె దుకాణం. కుడి: దుకాణం లోపల గోడలు కొంతభాగం అతను తయారు చేసిన జుత్తీలతో నిండి ఉంటాయి. 

Hansraj has been practicing this craft for nearly half a century. He rolls the extra thread between his teeth before piercing the tough leather with the needle

ఈ పనిని హన్స్ రాజ్ దాదాపు అర్థ శతాబ్దంగా చేస్తున్నారు. గట్టి తోలులోకి సూది దించేముందు దారాన్ని పళ్ల మధ్య పట్టి తిప్పుతారు.

Leaning against the weathered wall, he spends the next 12 hours crafting handmade shoes. The place where he leans his tired back on the wall is patchy – the cement has worn off exposing the bricks underneath. “The body aches, especially the legs,” Hans Raj says, massaging his knee joints. In summer, he says, “We get dane je [boils] on the back from all the sweating that causes pain.”

మాసిపోయిన ఆ గోడకి ఆనుకుని కూర్చుని, ఆయన రోజుకి పన్నెండు గంటల పాటు చేతితో చెప్పులు కుడుతూనే ఉంటారు. అతను అలసిపోయిన వీపుని ఆన్చి కూర్చునే చోట గోడ అరిగిపోయి ఉంది - సిమెంటు పెచ్చులు రాలి లోపల  ఉన్న ఇటుకలు కనిపిస్తున్నాయి. "ఒళ్ళు నొప్పులుగా ఉంటుంది, కాళ్లయితే మరీనూ," అంటారు హన్స్ రాజ్, తన మోకాళ్ళ చిప్పలు రుద్దుకుంటూ. "వేసవి కాలంలో చెమట పోసి, వీపు మీద వచ్చే దానే జా (కురుపులు) బాగా నొప్పి పెడతాయి," అంటారు. 

Hans Raj learnt the craft when he was around 15, and he was tutored by his father.  “I was more interested in exploring the outdoors. Some days I would sit down to learn, some days I would not.” But as he grew up and the pressure to work increased, so did the hours of being seated.

హన్స్ రాజ్ తనకి పదిహేనేళ్ళ వయసులో, వాళ్ళ నాన్న దగ్గర ఈ వృత్తివిద్య నేర్చుకున్నారు. "అప్పట్లో నాకు బయట తిరగటం మీద ఎక్కువ ఆసక్తి ఉండేది. కొన్నిరోజులు కూర్చుని నేర్చుకునే వాడిని, కొన్నిరోజులు లేదు." అయితే అతను పెద్దవాడు అయ్యే కొద్దీ పని చేయాలన్న వత్తిడి, కూర్చునే గంటలూ పెరిగాయి. 

Speaking in a mix of Punjabi and Hindi he says, “this work needs bariki [precision].”  Hans Raj has been working without glasses for years, “but I have started noticing changes to my eyesight now. If I work for many hours, my eyes feel the strain. I see two of everything.”

పంజాబీ, హిందీ కలిపిన భాష మాట్లాడుతూ ఆయన, "ఈ పనికి చాలా బారీకీ (ఖచ్చితత్వం) కావాలి," అంటారు. ఇన్ని సంవత్సరాలుగా 
కళ్ళద్దాల అవసరం లేకుండానే పనిచేశారు కానీ, "ఈ మధ్య కంటిచూపులో తేడా తెలుస్తుంది. కొన్ని గంటలు పనిచేసిన తర్వాత కళ్ళకి అలసట వస్తుంది. అన్నీ రెండుగా కనబడతాయి."

During a regular work day, he drinks tea and listens to the news, songs and cricket commentary on his radio. His favourite programme is the “ pharmaishi programme,” where listeners’ request of old Hindi and Punjabi songs are played. He himself has never called up the radio station to request any song saying, “I don’t understand numbers and can’t dial.”

అతను మామూలు పని రోజుల్లో టీ తాగుతూ, రేడియోలో పాటలు, వార్తలు, క్రికెట్ వ్యాఖ్యానము వింటూ ఉంటారు. శ్రోతలు కోరిన హిందీ, పంజాబీ పాటలు వినిపించే 'ఫర్మాయిషీ కార్యక్రమం' అతనికి ఇష్టమైన కార్యక్రమం. అయితే, అతను ఎప్పుడూ ఆ కార్యక్రమానికి ఫోను చేయలేదు. "నాకు అంకెలు అర్థం కావు, ఫోను కలపలేను," అంటారు. 

'I always start by stitching the upper portion of the jutti from the tip of the sole. The person who manages to do this right is a craftsman, others are not',  he says

'నేను ఎప్పుడూ చెప్పు అడుగు అట్ట కొననుంచీ జుత్తీ పై భాగం కుట్టటంతో మొదలు పెడతాను. అలా సరిగ్గా కుట్ట గలిగిన వాడు పని తెలిసిన కళాకారుడు, లేకపోతే లేదు', అంటారు ఆయన. 

Hans Raj has never been to school, but finds great joy in exploring new places beyond his village, especially with his friend, a holy man in the neighbouring village: “Every year we take a trip. He has his own car, and he often invites me to join him on travels. Together, with one or two more people, we’ve visited places in Haryana and Alwar and Bikaner in Rajasthan.”

హన్స్ రాజ్ బడికి ఎప్పుడూ వెళ్లలేదు కానీ వాళ్ళ ఊరు దాటి కొత్త కొత్త ప్రదేశాలు చూడటం అంటే అతనికి ఎంతో సంతోషం. పక్క ఊళ్ళో మతపెద్దగా ఉన్న స్నేహితుడితో కలిసి వెళుతుంటారు. "ప్రతి సంవత్సరం, ఒక యాత్ర చేస్తాము. అతనికి సొంత కారు ఉంది, అందులో నన్ను కూడా తీసుకు వెళతాడు. ఇంకొక ఇద్దరు ముగ్గురితో కలిసి, మేము హర్యానాలో చాలా స్థలాలు, రాజస్థాన్ లో అల్వార్, బికనేర్ తిరిగి చూసాము."

*****

It is well past 4 p.m, and Rupana village is bathed in the warm glow of a lingering mid-November sun. One of Hans Raj's loyal customers has arrived with a friend to pick up a pair of Punjabi juttis . “Could you also make a jutti for him by tomorrow?” he asks Hans Raj. The friend has come from far away – Tohana in Haryana – 175 kilometres from here.

అప్పటికి సాయంత్రం నాలుగు గంటలు దాటేసింది. రూపానా గ్రామం వదిలి పోలేక పోతున్న చలికాలపు సూర్యుడి వెచ్చటి వెలుగుతో నిండిపోయింది. ఎప్పటి నుంచో హన్స్ రాజ్ దగ్గర జుత్తీలు కొంటున్న ఖాతాదారుడు ఒకాయన, తన స్నేహితుణ్ణి కూడా తీసుకుని వచ్చారు. "ఇతనికి కూడా ఒక జుత్తీ కావాలి. రేపటి కల్లా చేస్తారా?" అని అడుగుతున్నారు అతను. ఆ స్నేహితుడు ఎంతో దూరం నుంచీ - హర్యానాలోని తోహానా - అంటే 175 కిలోమీటర్ల దూరం నుంచీ వచ్చారు.    

Hans Raj smiles, responding to the customer’s request with a friendly, “ yaar , it is not possible by tomorrow.” The customer, however, is persistent: “Muktsar is renowned for Punjabi juttis .” The customer then turns to us saying, “there are thousands of jutti shops in the city. But here in Rupana, it is only he who crafts them by hand. We are familiar with his work.”

హన్స్ రాజ్ చిన్నగా నవ్వుతూ, స్నేహంగా సమాధానం ఇచ్చారు, "రేపటికల్లా అంటే కుదరదు." అయితే ఆ వచ్చిన ఖాతాదారుడు వదలలేదు: "ముక్తసర్ పంజాబీ జుత్తీలకి పేరు మోసింది." అతను మావైపు తిరిగి, "పట్నంలో వేల కొద్దీ జుత్తీ దుకాణాలు ఉన్నాయి. కానీ ఇక్కడ రూపానాలో చేతితో జుత్తీలు తయారు చేసేది ఇతను ఒక్కడే. మాకు ఇతని పనితనం బాగా తెలుసు.."

The customer tells us that till Diwali, the entire shop was filled with juttis . A month later in November, only 14 pairs remain. What makes Hans Raj’s juttis so special? “The ones he makes are flatter in the middle,” the customer says, pointing to the juttis hanging on the wall, “The difference lies in the hands [of the craftsperson].

కొనటానికి వచ్చిన ఆయన, దీపావళి వరకూ మొత్తం దుకాణం నిండా జుత్తీలు ఉంటాయని చెప్పారు. ఒక నెల తర్వాత నవంబర్లో 14 జతలు మాత్రం మిగిలిఉన్నాయి. హన్స్ రాజ్ జుత్తీల ప్రత్యేకత ఏమిటి? "ఈయన చేసే జుత్తీలు మధ్యలో చదునుగా ఉంటాయి," గోడమీద జుత్తీలు చూపిస్తూ చెప్పారు. "ప్రత్యేకత పని తెలిసినవాడి చేతిలో ఉంటుంది."

‘There are thousands of jutti shops in the city. But here in Rupana, it is only he who crafts them by hand,’ says one of Hans Raj’s customers

'పట్నంలో వేల కొద్దీ జుత్తీ దుకాణాలు ఉన్నాయి. కానీ ఇక్కడ రూపానాలో చేతితో జుత్తీలు తయారు చేసేది ఇతను ఒక్కడే' అంటారు హన్స్ రాజ్ దగ్గర కొనేవాళ్ళలో ఒకరు 

Hans Raj doesn’t work alone – he gets some of the juttis stitched by Sant Ram, a skilled shoemaker in his native village, Khunan Khurd, 12 kms away. During Diwali or the paddy season, when the demand is high, he outsources his work, paying Rs. 80 for stitching a pair.

హన్స్ రాజ్ పని అంతా ఒక్కడే చేయరు - కొన్ని జుత్తీలు 12 కిలోమీటర్ల దూరంలో వాళ్ళ సొంత ఊరు ఖునన్ ఖుర్ద్ లో ఉండే సంత్ రామ్ అనే చెప్పులు కుట్టే నిపుణుడి చేత కుట్టిస్తారు. దీపావళి లేదా వరి పండే కాలంలో గిరాకీ ఎక్కువగా ఉన్నప్పుడు, ఒక్కొక్క జత 80 రూపాయల చొప్పున అతనితో కుట్టించుకుంటారు. 

The master shoemaker tells us the difference between a craftsman and a workman: “I always start by stitching the panna [upper portion] of the jutti from the tip of the sole. This is the most challenging phase of crafting juttis . The person who manages to do this right is a mistiri [craftsman], others are not.”

చేతి పని తెలిసిన కళాకారుడికీ, ఊరికే చేతి పనిచేసేవాడికీ తేడా ఏమిటో ఆయన ఇలా చెప్పారు: "నేను ఎప్పుడూ జుత్తీ యొక్క పన్నా (పై భాగం) అడుగు అట్ట చివరి నుంచీ కుట్టటం మొదలు పెడతాను. జుత్తీలు తయారు చేయటంలో ఇది అన్నిటికన్నా కష్టమైన భాగం. ఇది సరిగ్గా చేయగలిగిన వాడు మిస్త్రీ (చేతిపని తెలిసిన వాడు), లేకపోతే లేదు.."

It wasn’t a skill he learnt easily. “Initially, I was not good at stitching shoes with thread,” Hans Raj recalls. “But when I committed to learning it, I mastered it in two months.  The rest of the skill I picked up over time, first by asking my father, and later by observing him,” he adds.

అయితే, ఆ విద్య ఆయనకి సులువుగా ఏమీ రాలేదు. "మొదట్లో నాకు దారంతో చెప్పులు కుట్టటం సరిగ్గా వచ్చేది కాదు," అని గుర్తుచేసుకున్నారు హన్స్ రాజ్. "అయితే నేర్చుకోవాలని నేను నిశ్చయించుకున్న తర్వాత, రెండు నెలల్లో నేర్చేసుకున్నాను. ఇక మిగిలిన విద్య అంతా మెల్లగా నేర్చుకున్నాను. మొదట్లో మా నాన్నని అడిగి నేర్చుకునేవాడిని, తర్వాత చూసి నేర్చుకున్నాను."

Over the years, he has innovated, incorporating a technique of stitching small strips of leather on both sides of the jutti , seamlessly connecting all the joints. “These small strips add strength to the jutti . The shoes become more resistant to breakage,” he explains.

సంవత్సరాల తరబడి పని చేయటంలో, అతను కొన్ని కొత్త ప్రక్రియలు కనిపెట్టారు. జుత్తీకి రెండు వైపులా, అన్ని అతుకులనీ కలుపుతూ చిన్న తోలు ముక్కలు కుట్టటం వాటిలో ఒకటి.  "ఈ చిన్న ముక్కలు జుత్తీని బలంగా చేస్తాయి. చెప్పులు తొందరగా తెగకుండా ఉంటాయి," అని వివరించారు. 

The craft of jutti- making requires precision. ‘Initially, I was not good at stitching shoes with thread,’ he recalls. But once he put his mind to it, he learnt it in two months

జుత్తీలు కుట్టే విద్యలో ఖచ్చితత్వం చాలా అవసరం. 'మొదట్లో నాకు దారంతో చెప్పులు కుట్టటం సరిగ్గా వచ్చేది కాదు,' అని గుర్తుచేసుకున్నారు. అయితే, నేర్చుకోవాలని అనుకున్న తర్వాత, రెండునెలల్లో నేర్చేసుకున్నారు. 

Hans Raj and his family of four, including his wife, Veerpal Kaur, and two sons and a daughter – now married and parents themselves – relocated from Khunan Khurd to Rupana some 18 years ago. At that time, their eldest son, who is 36 now, began working at the paper mill in the village here.

హన్స్ రాజ్, అతని నలుగురు మనుషుల కుటుంబం - భార్య వీర్ పాల్ కౌర్, ఇప్పుడు పెళ్ళిళ్ళు చేసుకుని పిల్లలు ఉన్న ఇద్దరు కొడుకులు, ఒక కూతురు -  అందరూ ఖునాన్ ఖుర్ద్ నుండీ రూపానాకి 18 సంవత్సరాల క్రితం వచ్చారు. ఇప్పుడు 36 సంవత్సరాల వయసులో  ఉన్న వాళ్ళ పెద్ద అబ్బాయి అప్పుడు ఇక్కడ పేపర్ మిల్లులో పనిచేయటం మొదలు పెట్టారు. 

“It was mostly [Dalit] families who made juttis in Khunan Khurd, working from their homes. As time passed, the new generation didn’t learn the craft. And those who knew, passed away,” says Hans Raj.

"ఖునన్ ఖుర్ద్ లో జుత్తీలు తయారు చేసే కుటుంబాలు దాదాపుగా అందరూ దళితులే. ఇళ్లలోనే పనిచేసేవాళ్ళు. కాలం గడిచే కొద్దీ, కొత్త తరం ఆ విద్య నేర్చుకోలేదు. పని తెలిసిన వాళ్ళు చనిపోయారు," అన్నారు హన్స్ రాజ్. 

Today, in his old village, only three craftsmen, all from his community of Ramdasi Chamars (listed as Scheduled Caste in the state), are still engaged in the art of handcrafting Punjabi juttis while Hans Raj is the only one in Rupana.

ఇప్పుడు వాళ్ళ ఊళ్ళో ముగ్గురే చేతిపని కళాకారులు చేతితో పంజాబీ జుత్తీలు తయారు చేస్తున్నారు. అందరూ అతనిలాగే (ఆ రాష్ట్రంలో షెడ్యూల్ కులంగా గుర్తించబడిన) రామ్ దాసీ చమార్ కులానికి చెందినవారు. రూపానాలో అయితే హన్స్ రాజ్ ఒక్కరే మిగిలారు..

“We saw no future for our children in Khunan Khurd, so we sold our property there and bought one here,” Veerpal Kaur says, her voice a mix of determination and hope. She speaks fluent Hindi, a result of the diversity in the neighbourhood which is populated by migrants from Uttar Pradesh and Bihar, many of whom work in the paper mill and live in rented rooms in the vicinity.

మాకు ఖునన్ ఖుర్ద్ లో పిల్లలకి భవిష్యత్తు ఏమీ కనపడలేదు , అందుకే అక్కడ స్థలం అమ్మేసి ఇక్కడ కొనుక్కున్నాం," అని చెప్పారు వీర్ పాల్ కౌర్. ఆమె గొంతులో ఒక నిశ్చయం, ఒక ఆశ కలిసి వినిపించాయి. ఉత్తర ప్రదేశ్, బీహార్ రాష్ట్రాలనుంచీ వలస వచ్చిన చాలామంది ఇక్కడి పేపర్ మిల్లులో పనిచేస్తూ చుట్టుపక్కల అద్దె గదుల్లో ఉంటూ ఉంటారు. ఆ ప్రభావం వల్ల ఆమె చక్కటి హిందీ మాట్లాడుతున్నారు. 

Veerpal Kaur, Hans Raj’s wife, learnt to embroider juttis from her mother-in-law. She prefers to sit alone while she works, without any distractions

హన్స్ రాజ్ భార్య వీర్ పాల్ కౌర్, తన అత్తగారి వద్ద జుత్తీల పైన కుట్టుపని చేయటం నేర్చుకున్నారు. ఆమె ఒక్కరే కూర్చుని, ఏ కంగారూ లేకుండా పనిచేయటానికి ఇష్టపడతారు. 

It takes her about an hour to embroider one pair. She uses sharp needles that can pierce her fingers if she is not careful, Veerpal says

ఒక జత చెప్పుల మీద కుట్టుపని చేయటానికి ఆమెకు ఒక గంట వరకూ పడుతుంది. ఆమె వాడే సూదులు బాగా మొనదేలి ఉంటాయి.
జాగ్రత్తగా లేకపోతే చేతుల్లో గుచ్చుకుంటాయని అంటారు ఆమె. 

This is not the first time Hans Raj’s family has migrated. “My father came to Punjab from Narnaul [in Haryana] and started making juttis ,” says Hans Raj.

హన్స్ రాజ్ కుటుంబం వలస పోవటం ఇది మొదటిసారి ఏమీ కాదు. "మా నాన్న హర్యానాలోని నార్నాల్ నుంచీ ఇక్కడికి వచ్చి జుత్తీలు చేయటం మొదలుపెట్టారు," అంటారు హన్స్ రాజ్. 

A 2017 study by the Guru Nanak College of Girls in Sri Muktsar Sahib district shows that thousands of jutti -makers families migrated from Rajasthan to Punjab in the 1950s. Hans Raj’s ancestral village Narnaul is situated on the border of Haryana and Rajasthan.

2017 లో శ్రీ ముక్తసర్ సాహిబ్ జిల్లాలో ఉన్న గురు నానక్ మహిళా కళాశాల వారు చేసిన అధ్యయనంలో, 1950 ప్రాంతంలో జుత్తీలు తయారు చేసే వేల కొద్దీ కుటుంబాలు రాజస్థాన్ నుండీ పంజాబుకు వలస వచ్చాయని తేలింది. హన్స్ రాజ్ వాళ్ళ స్వంత ఊరు నార్నాల్ 
పంజాబు, హర్యానా సరిహద్దుల్లో ఉంది. 

*****

“When I started, a pair would only cost Rs. 30. Now a full embroidered jutti can cost over Rs 2,500,” Hans Raj recounts.

"నేను పనిచేయటం మొదలుపెట్టిన రోజుల్లో ఒక జత జుత్తీ 30 రూపాయలు ఉండేది. ఇప్పుడు పూర్తిగా కుట్టుపని చేసిన ఒక జత 2500 రూపాయల వరకూ ఉంది," అని గుర్తు చేసుకున్నారు హన్స్ రాజ్. 

From the small and large scattered pieces of leather at his workshop, Hans Raj shows us two kinds: cowhide and buffalo hide. “The buffalo hide is used for the sole, and the cowhide is for the upper half of the shoes,” he explains, his hands stroking the raw material that once formed the backbone of the craft.

తన దుకాణంలో చెదురు మదురుగా ఉన్న చిన్నా పెద్దా తోలు ముక్కలలో నుంచీ రెండు రకాల తోలు చూపించారు హన్స్ రాజ్: ఆవు 
తోలు, గేదె తోలు. "గేదె తోలు చెప్పు కింది భాగానికీ, ఆవు తోలు పై భాగానికీ వాడతాం," అని వివరించారు. తన వృత్తి విద్యకి ఒకప్పుడు వెన్నెముకగా నిలిచిన ముడి పదార్థాన్ని ఆయన చేతులు నిమురుతూ ఉన్నాయి. 

As he holds up the tanned cowhide he asks if we are comfortable touching the animal skin. When we express our willingness, he goes on to observe not just the tanned leather but the contrast. The buffalo hide feels as thick as 80 paper sheets stacked together. The cowhide, on the other hand, is much thinner, maybe around 10 paper sheets. In terms of texture, the buffalo hide has a smoother and stiffer feel, while the cowhide, though slightly rougher, exhibits greater flexibility and ease of bending.

పదును చేసిన ఆవు తోలు చూపిస్తూ పశువు చర్మం తాకటానికి మేము సిద్ధమేనా అని అడిగారు. మేము సరే అనగానే, ఆయన 
పదును చేయబడ్డ తోలు చూపించటమే కాక, రెండు రకాల మధ్య తేడాలు కూడా పరిశీలనగా చూపించారు. గేదె తోలు దాదాపు 80 కాగితాల బొత్తి అంత మందంగా ఉంది. ఆవు తోలు చాలా పల్చగా, బహుశా పది కాగితాల మందం ఉంది. తాకి చూస్తే, గేదె తోలు నునుపుగా, గట్టిగా ఉంది. ఆవు తోలు కొంచెం గరుకుగా ఉన్నా, మెత్తగా, తేలికగా వంగుతూ ఉంది. 

Hans Raj opens a stack of thick leather pieces that he uses to make the soles of the jutti . ‘Buffalo hide is used for the sole, and the cowhide is for the upper half of the shoes,’ he explains

హన్స్ రాజ్ తాను జుత్తీల అడుగు భాగాలకు ఉపయోగించే మందపాటి తోలు ముక్కల కట్ట విప్పి చూపించారు. 'గేదె తోలు చెప్పు అడుగు భాగానికీ, ఆవు తోలు పై భాగానికీ వాడతాము,' అని వివరించారు. 

Left: He soaks the tanned buffalo hide before it can be used. Right: The upper portion of a jutti made from cow hide

ఎడమ: పదును చేసిన గేదె తోలు ఉపయోగించటానికి ముందు నీళ్ళలో నానబెడతారు. కుడి: జుత్తీల పై భాగం ఆవు తోలుతో చేస్తారు. 

The growing hike in leather prices – his critical raw material – and the switch to shoes and slippers what he calls, “ boot-chappal ” has led to a fall in the number of people willing to take up this profession.

ఈ పనికి అత్యవసర ముడి పదార్థమైన తోలు రేట్లు పెరగటం, అందరూ 'బూట్-చెప్పల్' అని ఆయన పిలిచే బూట్లు, రబ్బరు చెప్పులు వాడటానికి ఎక్కువ ఇష్టపడటం, ఈ రెండు కారణాల వల్ల ఈ వృత్తిపని చేయటంలో ఎక్కువమంది ఆసక్తి చూపించటం లేదు. 

Hans Raj treats his tools with great care. For shaping the jutti he uses a rambi (cutter) to carve and scrape the leather; a morga (wooden hammer) for beating it until it is stiff and more. The wooden morga belonged to his father as did a deer horn which he uses to shape the tip of the shoes from inside as it is difficult to fix only with his hands.

హన్స్ రాజ్ తన పని ముట్లని ఎంతో జాగ్రత్తగా చూసుకుంటారు. జుత్తీలకు ఆకారాన్ని ఇవ్వటానికి రంబి(కత్తి)తో తోలును తొలుస్తారు; తోలు గట్టిపడే వరకూ మోర్గా (చెక్క సుత్తి)తో మోదుతారు. ఆ చెక్క మోర్గా, అలాగే చెప్పు లోపల నుండీ ఆకారాన్ని ఇచ్చే లేడి కొమ్ము, ఆయనకు వాళ్ళ నాన్న నుంచీ సంక్రమించాయి. ఆ లేడి కొమ్ము లేకుండా కేవలం చేతితో లోపలి ఆకారాన్ని తీసుకు రావటం చాలా కష్టం. 

The shoemaker travels to the shoe market in Jalandhar, 170 kms away from his village, to buy the tanned hides. To reach the mandi (wholesale market), he takes a bus to Moga and another from Moga to Jalandhar. His travel costs add up to over Rs. 200 one way.

పదును చేసిన తోళ్లు కొనుగోలు చేయటాని వాళ్ళ గ్రామం నుంచీ 170 కిలోమీటర్ల దూరంలో ఉన్న జలంధర్ వెళతారు. ఒక బస్సులో మోగా వరకూ, అక్కడ నుంచీ ఇంకొక బస్సులో జలంధర్ లోని మండీ (టోకు ధరల దుకాణం) వరకూ వెళతారు. వెళ్లటానికే ప్రయాణ ఖర్చులు 200 రూపాయల పైన అవుతాయి. 

His most recent journey took place two months prior to Diwali when he acquired 150 kilograms of tanned leather, valued at Rs. 20,000. Has he ever faced any trouble carrying the leather, we ask him. “The concern is more about transporting untanned leather than the tanned one,” he clarifies.

ఈ మధ్యనే దీపావళికి రెండు నెలల ముందు వెళ్ళి 20,000 రూపాయల విలువ చేసే 150 కిలోల పదును చేసిన తోలు తీసుకుని వచ్చారు. ఎప్పుడైనా అలా తోలు తీసుకు వచ్చేటప్పుడు ఇబ్బందులకు గురి అయ్యారా అని మేము అడిగాము. "పదును చేయని తోలు తీసుకు రావటం ఎక్కువ ఇబ్బంది," అని వివరించారు. 

Hans Raj takes great care of all his tools, two of which he has inherited from his father

హన్స్ రాజ్ తన పనిముట్లని చాలా జాగ్రత్తగా చూసుకుంటారు. రెండు పనిముట్లు వాళ్ళ నాన్న నుంచీ సంక్రమించినవి ఉన్నాయి. 

he wooden morga [hammer] he uses to beat the leather with is one of his inheritances

తోలు మోదటానికి వాడే చెక్క మోగా (సుత్తి) ఆయన వంశ పారంపర్య ఆస్తి 

He visits the mandi to carefully choose the desired quality of leather, and the traders arrange for its transportation to a nearby city, Muktsar where he collects it. “Carrying such heavy material alone on the bus is anyway not possible,” he remarks.

ఆయన మండీకి వెళ్ళి జాగ్రత్తగా చూసి తనకి కావలిసిన నాణ్యత ఉన్న తోలు ఎంచుకుంటారు. టోకు వ్యాపారి ఆ తోలును దగ్గరలో ఉన్న ముక్తసర్ పట్టణం వరకూ పంపిస్తే, ఆయన అక్కడి నుంచీ తెచ్చుకుంటారు. "అంత బరువైన సామాను ఒక్కడినే బస్సులో తీసుకురావటం కుదరదు కదా," అంటారు ఆయన. 

Over the years, the material for making juttis has evolved and younger shoemakers like Raj Kumar and Mahinder Kumar of the Guru Ravidas colony in Malout say that artificial leather such as rexine and micro cellular sheets are now more commonly used. Raj and Mahinder, both in their early forties, belong to the Dalit Jatav community.

కాలంతో పాటు జుత్తీలు తయారు చేయటానికి వాడే పదార్థాలు కూడా మారాయి. మాలౌత్ లోని గురు రవిదాస్ కాలనీలో ఉండే రాజ్ కుమార్, మహీందర్ కుమార్ వంటి పనివాళ్ళు రెక్సిన్, మైక్రో సెల్యులార్ షీట్లు ఇప్పుడు ఎక్కువగా వాడకంలో ఉన్నాయని అంటారు. దగ్గర దగ్గర నలభై ఏళ్ల వయసులో ఉన్న రాజ్, మహీందర్ దళిత జాతవ్ వర్గానికి చెందినవాళ్ళు. 

“Where a micro sheet cost Rs. 130 per kg, the cowhide now costs ranging from Rs. 160 to over Rs. 200 per kg,” says Mahinder. They say leather has become a rare commodity in the area. “Earlier, the colony was full of tanneries and a stench of untanned leather hung in the air. But as the basti grew, the tanneries were shut down,” says Raj.

"మైక్రో షీట్ కిలో 130 రూపాయలు అయితే ఆవు తోలు 160 నుండీ 200 వరకూ ఉంది," అన్నారు మహీందర్. ఆ చుట్టుపక్కల తోలు చాలా అరుదైన పదార్థంగా మారిందని అంటారు వాళ్ళు. "ఇంతకు ముందు కాలనీ నిండా తోలు పరిశ్రమలు ఉండేవి, అంతటా తోలు కంపు కొట్టేది. అయితే బస్తీ పెద్దది అయ్యే కొద్దీ అన్నీ తోలు పరిశ్రమలు మూత పడ్డాయి," అన్నారు రాజ్. 


Youngsters are no longer keen on joining the profession, they add, and low income is not the only reason. “The stench gets into the clothes,” Mahinder says, “and sometimes their friends won’t shake their hands.”

యువతరం ఈ వృత్తిలో చేరటానికి ఎక్కువ ఆసక్తి చూపటం లేదు. ఆదాయం తక్కువ అవటం ఒక్కటే కారణం కాదని అంటారు వాళ్ళు. "ఆ 
తోలు వాసన బట్టల్లోకి ఇంకి పోతుంది," అంటారు మహేందర్, "కొన్నిసార్లు వాళ్ళ స్నేహితులు కూడా వాళ్ళ చేతులు  ముట్టుకోవటానికి ఇష్టపడరు"

young shoemakers like Raj Kumar (left) say that artificial leather is now more commonly used for making juttis . In Guru Ravidas Colony in Malout where he lives and works, tanneries have shut

రాజ్ కుమార్ వంటి చెప్పులు కుట్టే యువకులు (ఎడమ) జుత్తీలు తయారు చేయటానికి కృత్రిమ తోలు వాడకం పెరిగిందని అంటున్నారు. 

వాళ్ళు ఉండే మలౌత్ లోని గురు రవిదాస్ కాలనీలో తోలు పరిశ్రమలు మూతపడ్డాయి. 

“In my own family the children don’t make juttis ,” says Hans Raj, “my sons never entered the shop to understand the craft, how could they have learned it? Ours is the last generation now to know the skill. I may also be able to do it for another five years, after me who else will do it?” he asks.

"మా ఇంట్లోనే పిల్లలు జుత్తీలు చేయటం లేదు," అంటారు హన్స్ రాజ్, "నా పిల్లలు దుకాణంలో అడుగుపెట్టరు, ఈ విద్యని అర్థం చేసుకుందామని అనుకోరు, మరి ఎలా నేర్చుకుంటారు? ఈ నైపుణ్యం ఉన్న చివరి తరం మాదే అవుతుంది. నేను కూడా మహా అయితే ఇంకో అయిదేళ్లు ఈ పని చేయగలను. నా తర్వాత ఈ పని ఎవరు చేస్తారు?" అని అడిగారు. 

As she chops vegetables for dinner, Veerpal Kaur says, “It isn’t possible to build homes by just making juttis . Almost two years ago, the family completed the construction of a pucca house, facilitated by their eldest son's employee loan from the paper mill.

రాత్రి భోజనానికి కూరగాయలు కోస్తూ, వీర్ పాల్ కౌర్ "జుత్తీలు కుట్టుకుంటూ ఇల్లు కట్టుకోవటం జరిగే పని కాదు," అన్నారు. దాదాపు రెండు సంవత్సరాల క్రితం, వాళ్ళ పెద్ద అబ్బాయి పని చేసే పేపరు మిల్లు నుంచీ తీసుకున్న లోను సహాయంతో వాళ్ళు ఒక పక్కా ఇల్లు కట్టుకోగలిగారు. 

“I had also asked her to learn embroidery, but she didn’t learn it all,” Hans Raj says, teasing his wife . The two have been married for 38 years. “I wasn’t interested,” Veerpal chimes back. Based on what she learnt from her mother-in-law, she can embroider a pair in an hour at home with zari thread.

"నేను కూడా ఈమెని కుట్టుపని నేర్చుకొమ్మని చెప్పాను, కానీ ఆమె అసలు నేర్చుకోనే లేదు," తన భార్యని ఆటపట్టిస్తూ అన్నారు హన్స్ రాజ్. వాళ్ళు పెళ్లి చేసుకుని 38 సంవత్సరాలు అవుతుంది. "నాకు ఇష్టం లేక పోయింది," వెంటనే అన్నారు వీర్ పాల్. తన అత్తగారి దగ్గర నేర్చుకున్న పనితో ఆమె జరీ దారంతో ఒక గంటలో ఒక జత జుత్తీల పైన కుట్టుపని చేయగలరు. 

Their home, shared with their eldest son's family of three, comprises two rooms, a kitchen, and a drawing room, with an outdoor toilet. Adorning the rooms and hall are photos of B.R. Ambedkar and Sant Ravidas. A similar image of the saint graces Hans Raj’s workshop.

వాళ్ళు, వాళ్ళ పెద్దబ్బాయి వాళ్ళ ముగ్గురు కుటుంబమూ కలిసి ఉండే ఆ ఇంట్లో రెండు గదులు, ఒక వంట గది, ఒక ముందు గది, బయట మరుగు దొడ్డి ఉన్నాయి. గోడల మీద బి. ఆర్. అంబేద్కర్, సంత్ రవిదాస్ ల ఫోటోలు అలంకరించి ఉన్నాయి. ఇటువంటిదే  సంత్ రవిదాస్ ఫోటో ఒకటి  హన్స్ రాజ్ దుకాణంలో కూడా ఉంది. 

hans Raj’s juttis have travelled across India with their customers. These are back in vogue after a gap of about 15 years. Now, ‘every day feels like Diwali for me,’ a joyous Hans Raj says

హన్స్ రాజ్ తయారు చేసిన జుత్తీలు కొన్న వాళ్ళతో కలిసి భారత దేశం అంతా ప్రయాణం చేశాయి. దాదాపు 15 సంవత్సరాల తర్వాత ఇప్పుడు మళ్ళీ ఈ రకం చెప్పులు ప్రాచుర్యం లోకి వచ్చాయి. ఇప్పుడు 'ప్రతి రోజూ నాకు దీపావళి,' అన్నారు హన్స్ రాజ్ సంతోషంగా. 

“It is in the last 10-15 years that people have started wearing juttis again,” Veerpal says,“before that, many had also stopped asking for the shoemakers.”

"ఈ పది పదిహేను ఏళ్ళలో అందరూ మళ్ళీ జుత్తీలు వాడటం మొదలుపెట్టారు," అన్నారు వీర్ పాల్, "అంతకు ముందు అసలు చెప్పులు కుట్టే వాళ్ళని తలుచునే వాళ్ళే లేరు"

During that time, Hans Raj worked as a farm labourer and occasionally crafted juttis within a day or two when a customer came by.

ఆ రోజుల్లో హన్స్ రాజ్ పొలం పనులు చేసేవారు. ఎప్పుడైనా ఎవరైనా అడిగితే ఒకటి రెండు రోజుల్లో జుత్తీలు కుట్టి ఇచ్చేవారు. 

“Now, more college going boys and girls are interested in wearing these juttis ,” Veerpal says.

"ఇప్పుడు కాలేజీ అబ్బాయిలు, అమ్మాయిలు ఇవి వేసుకోవటానికి ఇష్టపడుతున్నారు," అన్నారు వీర్ పాల్. 

Customers have also carried juttis to various places, including Ludhiana, Rajasthan, Gujarat, and Uttar Pradesh. Hans Raj fondly recalls crafting eight pairs of Punjabi juttis for a mill worker during his last big order. The mill worker purchased them for his relatives in Uttar Pradesh.

కొనుగోలుదారులు జుత్తీలని లూధియానా, రాజస్థాన్, గుజరాత్, ఉత్తర ప్రదేశ్ ఇలా రకరకాల ప్రదేశాలకి తీసుకు వెళ్లారు కూడా. ఒక పెద్ద కొనుగోలు గుర్తు చేసుకున్నారు హన్స్ రాజ్ - మిల్లులో పనిచేసే ఒకరి కోసం ఎనిమిది జతలు తయారు చేశారు. ఆ కొనుగోలు చేసిన ఆయన ఉత్తర ప్రదేశ్ లో తన బంధువుల కోసం తీసుకు వెళ్లారు. 

Since there’s a consistent demand for his craftsmanship in his current location, “Every day feels like Diwali for me,” a joyous Hans Raj says.

ఇప్పుడు ఉన్నచోట తన నైపుణ్యానికి తగిన పని ఉండటంతో, "ప్రతిరోజూ దీపావళి లాగే ఉంది," అంటారు హన్స్ రాజ్ సంతోషంగా. 

In November 2023, a few weeks after this story was reported, Hans Raj suffered a partial stroke. He is now recovering.

ఈ కథనం ప్రచురించిన కొన్ని వారాలకు, 2023 నవంబరులో హన్స్ రాజ్ పాక్షిక పక్షవాతానికి గురయ్యారు. ఇప్పుడు కోలుకుంటున్నారు. 






This story is supported by a fellowship from Mrinalini Mukherjee Foundation (MMF).

మృణాళిని ముఖర్జీ ఫౌండేషన్ ఇచ్చిన ఫెలోషిప్ ఈ కథనానికి సహాయపడింది. 

#leather #dalit #leather-worker #dalit-communities #craftpersons

#తోలు #దళితులు #తోలు-పనివారు #దళిత-సమూహాలు #చేతివృత్తులవారు 

Sanskriti Talwar

సంస్కృతి తల్వార్ 

Sanskriti Talwar is an independent journalist based in New Delhi, and a PARI MMF Fellow for 2023.

సంస్కృతి తల్వార్ న్యూ ఢిల్లీలో ఉండే స్వతంత్ర పత్రకారులు, 2023 సంవత్సరానికి PARI MMF ఫెలో కూడా. 


Naveen Macro

నవీన్ మాక్రో 

Naveen Macro is a Delhi-based independent photojournalist and documentary filmmaker and a PARI MMF Fellow for 2023.

నవీన్ మాక్రో ఢిల్లీలో ఉండే స్వతంత్ర ఛాయాచిత్ర పత్రకారులు. ఆయన డాక్యుమెంటరీలు తీస్తారు, 2023 సంవత్సరానికి PARI MMF ఫెలో కూడా.  


Editor : Sarbajaya Bhattacharya

Sarbajaya Bhattacharya is a Senior Assistant Editor at PARI. She is an experienced Bangla translator. Based in Kolkata, she is interested in the history of the city and travel literature.

సంపాదకులు: సర్బజయ భట్టాచార్య 

సర్బజయ భట్టాచార్య PARI లో సీనియర్ సంపాదకులు. ఆమె అనుభవజ్ఞులైన బంగ్లా అనువాదకులు. ఆమె కలకత్తాలో ఉంటారు. ఆ నగరపు చరిత్ర, యాత్రా సాహిత్యమూ ఆమెకు ఇష్ట విషయాలు. 