---
categories:
- book-review
- philosophy
date: '2019-10-08T17:34:20+05:30'
title: Myth of Sisyphus
---

Thanks for all the wishes, guys and gals!

 (This was written on 7th November 2018 😊)

 As I have had a leisurely day and not an overwhelming number of wishes, I have actually been able to reply to most of you individually. 🙂

 While replying to a friend with a witty remark, realised that I share my birthday with Albert Camus, who has been my favorite philosopher forever and was encouraged by this fortuitous discovery to re\-read his Myth of Sisyphus. Here are a few extracts that made my day! By the way, read in sequence, they kind of capture the essence of the essay too…

 \=\=\=\=\=

 There is but one truly serious philosophical problem, and that is suicide. Judging whether life is or is not worth living amounts to answering the fundamental question of philosophy. \[…]

 This world in itself is not reasonable, that is all that can be said. But what is absurd is the confrontation of this irrational and the wild longing for clarity whose call echoes in the human heart. The absurd depends as much on man as on the world. \[…]

 Does its absurdity require one to escape it through hope or suicide—this is what must be clarified, hunted down, and elucidated while brushing aside all the rest. Does the Absurd dictate death? \[…]

 Let us insist again on the method: it is a matter of persisting. At a certain point on his path the absurd man is tempted. History is not lacking in either religions or prophets, even without gods. He is asked to leap. All he can reply is that he doesn’t fully understand, that it is not obvious. \[…]

 Suicide, like the leap, is acceptance at its extreme. Everything is over and man returns to his essential history. His future, his unique and dreadful future—he sees and rushes toward it. In its way, suicide settles the absurd. It engulfs the absurd in the same death. \[…]

 If I convince myself that this life has no other aspect than that of the absurd, if I feel that its whole equilibrium depends on that perpetual opposition between my conscious revolt and the darkness in which it struggles, if I admit that my freedom has no meaning except in relation to its limited fate, then I must say that what counts is not the best living but the most living.

 The most living; in the broadest sense, that rule means nothing. It calls for definition.

 Being aware of one’ s life, one’ s revolt, one’ s freedom, and to the maximum, is living, and to the maximum. Where lucidity dominates, the scale of values becomes useless.

 Thus, it is that no depth, no emotion, no passion, and no sacrifice could render equal in the eyes of the absurd man (even if he wished it so) a conscious life of forty years and a lucidity spread over sixty years.

 Thus I draw from the absurd three consequences, which are my revolt, my freedom, and my passion.

 By the mere activity of consciousness I transform into a rule of life what was an invitation to death—and I refuse suicide.

<!--
post-647
https://venugvgk.wordpress.com/2019/10/08/myth-of-sisyphus/
-->
