---
categories:
- musings
date: '2021-05-05T09:31:53+05:30'
title: Subba in 2021
---

It has been 4 years since Subba passed away. I first met him in 2006, when we went to Timbactu to study their education model as part of a course in Social Entrepreneurship.

 Below are a few extracts from a report we submitted at the end of the project. Also sharing a post I wrote last year, about 15 years later, which kind of compliments the writing below.

 In the last 15 years, I have not come across a single reason to change my opinion about Subba, his passion, dedication, and overall awesomeness. We are fortunate to have known him, and at Sambhavam and Farm Hill, we continue to be guided by his vision and wisdom and celebrate him practically every day.

 Begin Quote:

 Our first reaction on seeing Subba was one that of disbelief. The principal question bothering our minds was why would a doctorate from an IIT choose to teach primary school children and live a lifestyle that is incredibly so simple? To top it all, he was not even from an elite family which was already well off. He was in fact a first\-generation literate from a family which perhaps needed his financial support. As stated earlier, he did not fall into any of our known paradigms of life.<br>
…<br>
When asked to Subba himself, he kind of got around the question saying that he did not like a “nine to five” job and was perhaps lazy to do the usual jobs that he could have got. Of course, he did talk about his dreams from childhood on ‘changing the country’ and ‘providing high quality education to every child’. Though these childhood dreams explain to some extent his current passion, they do not explain them in their entirety. There are obviously some other factors too which made him embrace his current lifestyle.<br>
…

 Subba for us, personified the very anti\-thesis of the incentive\-based mechanism that we were so much used to as MBA students. By being with him and talking to him, we were able to recognize and appreciate that other forms of mechanisms were possible as well. This apart, his humility and modesty were some things that ought to be seen to be believed. Very rarely do people come across with the entire package – passion, dedication, open mindedness, intelligence and humility. Suffice to say that, we consider ourselves lucky to have had the chance to meet him.



---

 When questioned about expectations from his children, he says that they would be given Timbaktu education till they reach tenth standard so that they have a ‘happy childhood’. Later, they could pursue their own interests. Developing self\-reliance and enjoying one’s childhood are the key things that he wants to give them. He believes that his children would understand this paradigm in the future.



---

 These things apart, our own perception of what constitutes a good education for a child (the original problem that we started with) also has changed. So much so that, if we were to think or talk about education some time down the line, ‘happy childhood’ and ‘joy of learning’ would be the foremost in our minds.



---

 In effect, it is not necessary for Bablu or Mary or Subba to set up Timbaktus all over. If the rest of the world can see, learn and adopt this model where “providing a happy childhood” is the most important mandate of a school that would be success enough.

 End Quote.

<!--
post-745
https://venugvgk.wordpress.com/2021/05/05/subba-in-2021/
-->
