---
categories:
- musings
date: '2010-09-02T13:18:30+05:30'
title: 'Babaspeak: Understanding self'
---

After a particularly lengthy discourse by IIMbaba, Senior Bhakta got hold of the Junior Baba (who was the Senior Bhakta before he jumped ship in to baba\-hood) while coming out and proceeded to ‘try and summarize the discussion’, as was his habit, ‘just to see’ that he ‘understands it correctly’.

 He concluded his summary with a question: “so, the bottom line of what the Baba was saying is that discovering and understanding oneself is the route to freedom and happiness. What has your experience been as a practitioner?”

 Junior Baba replied rather candidly, despite his impending baba\-hood: “While I would take Baba’s word on such matters anyday, critical self exploration, at least in the initial stages, is very very far from happiness. There is very little prettiness for anyone to see there”

<br>

<!--
post-185
https://venugvgk.wordpress.com/2010/09/02/iimbaba-understanding-self/
-->
