---
categories:
- philosophy
date: '2021-02-24T10:00:30+05:30'
title: JK on Dialogue
---

<br>
JK demonstrating the process of dialogue with oneself, through a dialogue about love, attachment and freedom.

 [https://jkrishnamurti.org/content/dialogue\-oneself\-0](https://jkrishnamurti.org/content/dialogue-oneself-0)

 Here is a summary:

 Thought has created the loneliness, loneliness seeks attachment and this attachment is what we think is love, most of the time. That’s why most of our love is attachment and jealousy.

 Now the key point he makes is that unless thought itself, meaning every person’s own thinking itself, starts to see this, repeat, start to see this by itself, without any external imposition of this idea, there is no freedom.

 Unless your thinking itself sees this, this very idea becomes another thought created by thinking and imposed upon your mind. That leads to conflict.

 A couple of thoughts (now, it’s difficult to not smile when using this word in this context here. ):

 Reading some of these notes, I see how extraordinarily difficult it is for this to happen. Once I have heard this idea, how difficult it is to not accept it as another dictum, and to start independently and seek it for myself! How difficult not to think that I have now had this realization and feel the pleasure of that enlightenment! This is like trying to forget what one knows. It’s like how a child who has already read about and has seen pictures of pollination struggles to actually observe the process. But all analogies fail, naturally.

 Also, how extraordinarily difficult it is to convey any of this..The very language becomes a hindrance. The words just fail sometimes.

<!--
post-709
https://venugvgk.wordpress.com/2021/02/24/jk-on-dialogue/
-->
