---
categories:
- books
date: '2010-09-30T11:32:52+05:30'
title: The Pleasures of a Lexophile
---

As such, I love words. And these days I have been teaching Verbal Ability classes for CAT (I know, I know, what to do? One has to eat, no?) and GRE. So, I spend enough and more time on words.

 I thought there should be a word for a word\-lover and hazarding a guess, came up with ‘Lexicophile’. When I fed the word to google, it told me the word is actually ‘Lexophile’ and this [blog link](http://blog.gadodia.net/define-lexophilia/) came up. While there are more nuances to words apart from ‘plain, hilarious pun’, the collection on this page is very good and entertaining. I will put a couple of samples here now:

 ***The Police were called to a daycare where a 3 year old was resisting a rest.***

 ***Santa’s helpers are subordinate clauses.***

 The blog also said “The Wikipedia defines [Lexophilia](http://en.wikipedia.org/wiki/Lexophilia) as the love of words and a Lexophile as a lover of words who generally appreciate the nuances surrounding different words “. Naturally I clicked on the Wikipedia link and it told me that the page is deleted. So, I looked it up in Wictionary and there, the suggested word for a love of words and word games is ‘Logophilia’.

 **I think** ‘lexophilia’ is better than ‘logophilia’and **therefore I am** a Lexophile.

 Anyway, now that we settled on the nomenclature, there are some books that I want to talk about.

 The first one is [The meaning of Liff](http://folk.uio.no/alied/TMoL.html#anchorN#anchorN) by Douglas Adams and John Lloyd. This is what they have to say in the very short foreword:

 In Life\*, there are many hundreds of common experiences, feelings, situations and even objects which we all know and recognize, but for which no words exist. On the other hand, the world is littererd with thousands of spare words which spend their time doing nothing but loafing about on signposts pointing at places. Our job, as wee see it, is to get these words off the signposts and into the mouths of babes and sucklings and so on, where they can start earning their keep in everyday conversation and make a more positive contribution to society.

 Douglas Adams<br>
 John Lloyd

 \*And, indeed, in Liff.

 Some samples of the words that they come up with:

 **BABWORTH (n.)**<br>
 Something which justifies having a really good cry.

 **BOTCHERBY (n.)**<br>
 The principle by which British roads are signposted.

 **GRINSTEAD (n.)** The state of a lady’s clothing after she has been to powder her nose and has hitched up her tights over her skirt at the back, thus exposing her bottom, and has walked out without noticing it.

 **LIFF (n.)**<br>
 A book, the contents of which are totally belied by its cover. For instance, any book the dust jacket of which bears the words. ‘This book will change your life’.

 **LULWORTH (n.)**<br>
 Measure of conversation. A lulworth defines the amount of the length, loudness and embarrassment of a statement you make when everyone else in the room unaccountably stops talking at the same time

 I will now make an effort and stop putting more samples here…..Okay, two more.

 **PELUTHO (n.)**<br>
 A South American ball game. The balls are whacked against a brick wall with a stout wooden bat until the prisoner confesses.

 **SMARDEN (vb.)**<br>
 To keep your mouth shut by smiling determinedly through you teeth. Smardening is largely used by people trying to give the impression that they’re enjoying a story they’ve heard at least six times before.

 Done now. The next book is again an effort in lexicography – [The Devils Dictionary](http://www.gutenberg.org/files/972/972-h/972-h.htm) by Ambrose Bierce.  Here is the Wikipedia [entry](http://en.wikipedia.org/wiki/The_Devil's_Dictionary) for some more background. Once again, I take the liberty of quoting.

 From the Preface:

 *The Devil’s Dictionary* was begun in a weekly paper in 1881, and was continued in a desultory way at long intervals until 1906\. In that year a large part of it was published in covers with the title *The Cynic’s Word Book*, a name which the author had not the power to reject or happiness to approve. To quote the publishers of the present work:

 “This more reverent title had previously been forced upon him by the religious scruples of the last newspaper in which a part of the work had appeared, with the natural consequence that when it came out in covers the country already had been flooded by its imitators with a score of ‘cynic’ books—*The Cynic’s This*, *The Cynic’s That*, and *The Cynic’s t’Other*. Most of these books were merely stupid, though some of them added the distinction of silliness. Among them, they brought the word ‘cynic’ into disfavor so deep that any book bearing it was discredited in advance of publication.”

 Some words from the book:

 **ARMOR**, n. The kind of clothing worn by a man whose tailor is a blacksmith.

 One entry after my own heart.

 **BACCHUS**, n. A convenient deity invented by the ancients as an excuse for getting drunk.


```
  Is public worship, then, a sin,       That for devotions paid to Bacchus   The lictors dare to run us in,       And resolutely thump and whack us?
```
 Jorace

 I must confess now that I looked up this word just now and it has adequately met my expectations.

 **IDIOT,** n. A member of a large and powerful tribe whose influence in human affairs has always been dominant and controlling. The Idiot’s activity is not confined to any special field of thought or action, but “pervades and regulates the whole.” He has the last word in everything; his decision is unappealable. He sets the fashions and opinion of taste, dictates the limitations of speech and circumscribes conduct with a dead\-line.

 Some entries are outright enlightening and some, at once pregnent with meaning.

 **INK**, n. A villainous compound of tannogallate of iron, gum\-arabic and water, chiefly used to facilitate the infection of idiocy and promote intellectual crime. The properties of ink are peculiar and contradictory: it may be used to make reputations and unmake them; to blacken them and to make them white; but it is most generally and acceptably employed as a mortar to bind together the stones of an edifice of fame, and as a whitewash to conceal afterward the rascal quality of the material. There are men called journalists who have established ink baths which some persons pay money to get into, others to get out of. Not infrequently it occurs that a person who has paid to get in pays twice as much to get out.

 **IMPIETY**, n. Your irreverence toward my deity

 **IMPUNITY**, n. Wealth.

 **LIBERTY**, n. One of Imagination’s most precious possessions.


```
  The rising People, hot and out of breath,   Roared around the palace:  "Liberty or death!"   "If death will do," the King said, "let me reign;   You'll have, I'm sure, no reason to complain."
```
 Martha Braymance

 Okay. I will now have to stop for the fear that I will end of pasting the book here.

 The third (and the last) book for the day is [‘Fantastic Fables’](http://www.gutenberg.org/files/374/374-h/374-h.htm) by Ambrose Bierce. These are short pieces written with sardonic wit and sometimes, outright black humor. For those of you aspiring to crack the CAT and looking for the definition of satire, here it is.

 One sample:

 The Thoughtful Warden
---------------------

 <br>


 The Warden of a Penitentiary was one day putting locks on the doors of all the cells when a mechanic said to him:

 “Those locks can all be opened from the inside—you are very imprudent.”

 The Warden did not look up from his work, but said:

 “If that is called imprudence, I wonder what would be called a thoughtful provision against the vicissitudes of fortune.”

 <br>


 One more, before I stop for the day.

 The Christian Serpent
---------------------

 <br>


 A Rattlesnake came home to his brood and said: “My children, gather about and receive your father’s last blessing, and see how a Christian dies.”

 “What ails you, Father?” asked the Small Snakes.

 “I have been bitten by the editor of a partisan journal,” was the reply, accompanied by the ominous death\-rattle.

 Some of you, the nice guys who have been reading this blog for a while, might think that my Babaspeak articles are inspired by FF and you would be, unfortunately, completely wrong. I have come upon this book very recently. And anyway, Babaspeak is all IIMBaba’s doing. I am but the narrator.

 Alright, only one more fable:

 Father and Son
--------------

 <br>


 “My boy,” said an aged Father to his fiery and disobedient Son, “a hot temper is the soil of remorse.  Promise me that when next you are angry you will count one hundred before you move or speak.”

 No sooner had the Son promised than he received a stinging blow from the paternal walking\-stick, and by the time he had counted to seventy\-five had the unhappiness to see the old man jump into a waiting cab and whirl away.

 I will stop now. I want to look up more Ambrose Bierce.

<!--
post-217
https://venugvgk.wordpress.com/2010/09/30/the-pleasures-of-a-lexophile/
-->
