---
categories:
- musings
date: '2011-06-01T21:03:22+05:30'
title: The oak tree and the blades of grass
---

Once there was an oak tree. It grew big and strong, as oak trees generally do. It did not know any other way of growing. When wind blew, it moved happily but as it grew older, firmness set into its limbs.

 One monsoon, there grew a clump of grass under the oak tree. The blades of grass grew thin and straight, as blades of grass grow anywhere. They really danced with joy in the wind. The oak tree looked on, sighing.

 One day there was a storm. The blades of grass survived. The oak tree was uprooted. Same as happened countless times to countless other oak trees and blades of grass in countless other storms. But this time, a wise man was passing by. The wise man got immortalized by asking “which is stronger, a mighty Oak tree or a blade of grass?” and quickly answering “in a monsoon, the tree broke like a twig but the blades of grass that yielded remained standing.”

 As this observation took the form of a moral tale depicting the “fall of the proud oak tree”, the fallen but not yet dead oak tree also had to endure the taunts and boasts of the surviving grass blades. Till the time summer came and baked both the grass and the oak tree a dull, dead brown.

<!--
post-386
https://venugvgk.wordpress.com/2011/06/01/the-oak-tree-and-the-blades-of-grass/
-->
