---
title: A Sanskrit Bible story was written in Ayodhya
categories:
 - history
date: 2024-12-27
---

The point of all this is not to eulogise the bonhomie of premodern elites – Hindu, Christian, Muslim, Persianate or Sanskritic. What I want to argue is that syncretism and tolerance are not an inbuilt feature of Indian civilisation, which we can take for granted, pay lip service to, or chip away at for political profit. Despite many efforts at persecution and conversion, syncretism developed again and again through serious political and intellectual commitment. Invariably in Indian history, this has proved worth the effort, because it allowed for the influx, development, and spread of invigorating new ideas and possibilities — ideas uniquely Indian.

[the print article link](https://theprint.in/opinion/a-sanskrit-bible-story-was-written-in-ayodhya-the-patron-was-a-lodi-the-poet-a-kshatriya/2419202/)

anirudh kanisetti

After Timur Left: Culture and Circulation in Fifteenth-Century North India, by historian Aparna Kapadia