---
categories:
- poetry
- telugu
- translation
date: '2018-12-08T19:51:20+05:30'
title: Kahlil Gibran – Marriage – a translation
---

Marriage \|\| Kahlil Gibran in ‘The Prophet’

 మీ ఇద్దరి దగ్గరితనపు అల్లికలో<br>
 అక్కడక్కడా అందంగా ఖాళీలు ఉండనీ<br>
 స్వర్గలోకపు చిరుగాలులు<br>
 మీ మధ్య చొరబడి నాట్యం చేయనీ

 ఒకరిపై ఒకరి ప్రేమ, కట్టిపడేసే బంధంగా మారక,<br>
 మీ మనసుల తీరాల మధ్య చలిత సముద్రమవనీ

 ఒకే పాత్ర నుంచి ఇద్దరూ తాగాలనుకోక, ఒకరి పాత్ర నుంచి ఒకరు ఒంపుకోనీ,<br>
 ఒకే కంచంలో ఇద్దరూ తినబోక, ఒకరు తినేది ఇంకొకరితో పంచుకోనీ,

 కలిసి పాడుతూ ఆడుతూ సంతోషంగా సమయం సాగనీ,<br>
 అయినా ఎవరి ఏకాంతం వారికి ఉండనీ<br>
 ఒకే సంగీతంతో కలిసి స్పందించే, వీణా తంత్రులు విడివిడిగా ఒంటరివే

 మీ మనసులు ఇవ్వవలసిందే, కానీ ఒకరికి ఒకరు కాదు<br>
 జీవిత హస్తం మాత్రమే హృదయాలని అందుకునేది

 కలిసి నిలబడాలి కానీ మరీ దగ్గరగా కాదు<br>
 గుడి స్తంభాలు కొంచెం దూరదూరంగానే ఉంటాయి

 పైగా ఒక మహా వృక్షపు నీడలో ఇంకొకటి పెరగదు.

 Marriage \|\| Kahlil Gibran in ‘The Prophet’

 Let there be spaces in your togetherness,<br>
 And let the winds of the heavens dance between you.

 Love one another but make not a bond of love:<br>
 Let it rather be a moving sea between the shores of your souls.<br>
 Fill each other’s cup but drink not from one cup.<br>
 Give one another of your bread but eat not from the same loaf.<br>
 Sing and dance together and be joyous, but let each one of you be alone,<br>
 Even as the strings of a lute are alone though they quiver with the same music.

 Give your hearts, but not into each other’s keeping.<br>
 For only the hand of Life can contain your hearts.<br>
 And stand together, yet not too near together:<br>
 For the pillars of the temple stand apart,<br>
 And the oak tree and the cypress grow not in each other’s shadow.

<!--
post-638
https://venugvgk.wordpress.com/2018/12/08/kahlil-gibran-marriage-a-translation/
-->
