---
categories:
- musings
date: '2011-05-28T10:34:56+05:30'
title: Not eating eggs
---

I was once sharing rooms with a friend who did not eat eggs.

 Right. That’s what I remember him for – not eating eggs.

 I can hear you wondering – “What is so great about it? A lot of people do not eat eggs”.  His not eating eggs was different since he ate everything else – chicken, mutton and fish; possibly even beef and pork. May be not dog. But never ate eggs.

 It came out fairly early in my acquaintance with him. One evening we were out searching for food. We were not hungry enough to eat anything seriously non\-vegetarian but wanted something spicy. I suggested egg biriyani.  And pat came the reply – “I don’t eat eggs. Don’t ask me why.” I let it pass since I did not know him well enough. But the seed of the question that would haunt me later was planted in my head.

 I eat eggs every day, at least with one meal. Every time, I offered to make him some eggs and every time he refused. He would simply say “No”. He continued saying no to eggs even after he realized I was (I still am) a good cook.  I was intrigued.

 I initially wondered about how different he was in other respects – you know, skeletons in the closet kind of thing. And he kept his room door locked all the time. But as I slowly got to know him, I realized he was more or less a normal human being in all other aspects, except for not eating eggs.

 It became a constant thought with me. We would be sitting, watching TV together and I would suddenly look at him and wonder – “why doesn’t he eat eggs”? Or we would be taking a walk, there would be a lull in the conversation and eggs would pop in to my head.

 I started thinking more and more about it. I still did not know him well enough to press him for an answer. Maybe he thought of an egg in terms of the life it contains and possibly did not want to end a life not yet began. So, with my usual astuteness, I once led him to a discussion on “what came first – chicken or egg”. He did not show any pro\-egg sentiment throughout the one hour discussion. On another day, while cleaning the house, I noticed a nest of lizard eggs and covertly watched to see what he would do, half\-expecting him to start coochi\-cooing to them. He just gathered them up and put them in the dustbin. No – it was just not a pro\-life approach. But still he would not eat eggs.

  May be his family was in to chicken farming and he had grown sick of eating eggs everyday for the first 15 years of his life. A careful background check revealed that his father was a banker. No way.

 Another day, I fell asleep while watching a Hindi movie and had a dream. In that dream, my friend was a child of ten. His parents shut him up in a cellar by mistake and left for a long holiday. For fifteen days, he was stuck in the cellar with a large carton of eggs. Raw egg for breakfast, lunch and dinner. That would turn any one permanently off eggs. When I probed around his childhood, I discovered that he grew up in the middle of Delhi, in an apartment complex. That theory went out of the window.

 In another scenario I thought of, my friend had a chicken as a pet and was very close to it. He might have seen, up close, how hard it was to actually lay an egg. Think of one good friend you care about. Now imagine a fully inflated football coming out of his behind, one every day. And then imagine that is the only way of producing footballs – would you do anything that increases the demand for footballs? You wouldn’t. On careful thought, I let this go since you wouldn’t eat your friend either. My friend has no problems eating a full chicken for lunch.

 I was once rifling through his bookshelf and realized that there was a definite socialist, possibly even communist, slant to his reading. Then I recalled that there are two types of chicken – broilers and layers. Broilers are eaten and layers lay eggs. Was there a class struggle angle? Did he think of layers as the bourgeois middle class and did not want to have anything to do with them? Or did he see them as the worker class and does not want to participate in the ‘cruel exploitation’? Did he harbor the dream of bringing freedom and power to the exploited classes of chicken world? Again, obliquely approaching it through a high sounding intellectual discussion, I was disappointed to discover that he did not even know there are different classes of chicken. I also discovered, by some tactful questioning, that he had never been to a chicken farm in life.

 One Sunday morning, we had a ‘pure vegetarian’ friend visiting. While I was preparing bread and eggs for my breakfast, he looked at the eggs distastefully and had the gall to say that eggs stink. I had never thought of it that way – eggs smell delicious! Then it struck me. Maybe that is the reason my friend did not eat eggs. The next day I bought some dried fish and fried them while he was around. They stank so much I had to hold my nose while he was not looking. He was happily standing around offering random suggestions and ate a large share when it was done. So, it was not smell.

 By this time my stay in the city was coming to an end. We never grew any closer – maybe he was generally the reserved sort. Or maybe I put him off with my persistent probing, though I swear I was quite discreet and tactful.  Anyway, I could never ask him directly and I never found out why he didn’t eat eggs.

 Once in a while I still visit him when I travel to the city. He still does not eat eggs. May be he simply does not like the taste of them. Maybe he has an allergic reaction to something in eggs. Or maybe he was once bombed by alien chicken with their exploding eggs and has a permanent fear of eggs. I wouldn’t know.

<!--
post-382
https://venugvgk.wordpress.com/2011/05/28/not-eating-eggs/
-->
