---
title: Language Policy in India - Quick Thoughts
author: Venu GVGK
categories: Education Policy
date: 2026-04-09
---

In our 'Policy, Institutions and Practice' class in MAEE at TISS, a classmate made a wonderful presentation about the language policy in India. Towards the end, in characteristic fashion, the professor asked, "what would you do as a policy maker?" Here is a (paraphrased) summary of thoughts I shared. 

* We need to first acknolwedge the reality of the launguage situation in the country. We cannot operate from simplified notions of pedagogical soundness, linguistic identity, or national cohesion. Instead, we need to see this as a complex problem of policy design and implementation, with multiple stakeholders, competing interests, and trade-offs.

* While we may argue for mother tongue education from a pedagogical perspective, we need to consider the reality that mother tongues and regional language are not the same for many students. For example, a child from a tribal community/ a migrant community or simply from a certain demographic background may have a different mother tongue than the regional language used in schools. This creates a mismatch between the language of instruction and the child's linguistic background, which can lead to learning difficulties and dropouts. Therefore, we need to design language policies that are inclusive and flexible, allowing for multiple languages to be used in schools, and providing support for students who may not have access to the regional language at home. At the minimum, we need to deliberately build the bridges necessary for students to transition from their mother tongue to the regional language.

* English is definitely the language of aspiration and opportunity for many students and families. We also need to acknoledge that accessing higher education and employment opportunities necesarily require skills in English. Hence, it is important to provide access to English education. However, this is unlikely to be achieved by simply replacing regional language with English as the medium instruction from grade 1. Instead, we need to design a gradual and supportive transition to English, starting with regional language as the medium of instruction in the early grades, and then introducing English as a subject and eventually as a medium of instruction in higher grades. For example, we can start English as a subject in 2nd or 3rd grade, focusing more on building familiarity and fluency rather than technical knowledge of the langauge and have a goal that by 8th or 9th grade, students will build the necesary comfort to transition to English as medium of instruction. This would allow students to build a strong foundation in their mother tongue and regional language, while also developing proficiency in English over time.

* As a country, we need a link language and very clearly, even today, that link language is English. We need to keep notions of national cohesion and unity in mind, but we also need to be realistic about the fact that Hindi is not a viable link language for many students and families across the country. We need to move away from the idea of Hindi as a national language and instead embrace English as a link language that can connect people across different regions and linguistic backgrounds. 

* While we may all love our mother tongues and regional languages, and may dream of building them up as international languages, we need to be realistic and acknolwedge that this is unlikely to happen. Instead, we need to focus on preserving and promoting our linguistic diversity within the country, while also providing access to English education as a means of connecting with the global community.

In summary, we need to build bridges between mother tongues and regional langauges, between regional languages and English, and between pedagogical soundness, linguistic identity and economic mobility. Instead, what we have today is a lot of noise about promoting "indian languages" with focus on Hindi and Sanskrit on one hand and state governments trying to replace regional languages with English as medium of instruction from grade 1 on the other hand. We need to move away from these extremes and towards a more nuanced and inclusive language policy that recognizes the needs and limits of the various languages in structuring identity, pedagogy, and opportunity.