---
categories:
- musings
date: '2010-08-30T14:05:43+05:30'
title: Of bottle gourds and political stability
---

I am one of the breed derogatorily referred to as ‘bleeding hearts’. Among other things, we believe that organised retail drives small business out of the market and therefore it is bad. We are all for entrepreneurship and think that an unorganised/informal market is good for entrepreneurship. In fact, it has been argued (not always by bleeding hearts) that the presence of ‘a billion entrepreneurs’ is a factor working for Indian Economy.

 I took a course in Social Entrepreneurship at the B school. In one of the classes, I remember the professor getting indignant at the thought of house wives haggling with puch\-cart vegetable vendors over a couple of rupees. The push\-cart guy goes to the wholesale market at 5 am on foot and comes back (a likely distance of about 10 km) pushing about 20\-30 kg of vegetables. The idea is that it is indecent to deny that guy a couple of rupees for the effort. We all agreed with the professor.

 So, whenever I am entrusted with the task of buying vegetables, I go to the small market/push carts instead of going to the Heritage Fresh, a supermarket nearer home. Over a period of time, I have noticed that the price of vegetables is consistently higher in the market. Still, I used the ‘poor push\-cart guy’ argument and would pay the extra couple of rupees. The fact that the vegetables in the market are fresher than what the Heritage Fresh can offer, despite its infrastructure on the cold storage front, added a little practical rationale.

 Today, I went out to the market to buy some bottle gourd. I noticed that a push cart had really nice, tender looking ones. The lady manning the cart obviously saw my interest as I made way towards the cart. I didn’t probably help matters when I was specific about which gourds I wanted. I picked two (clearly weighing less than a kg) and she dropped a bombshell…twenty five rupees!! Even with my limited exposure to the market, I knew it was a clear case of over\-pricing. I had to start haggling and she refused to give any discount. While I was leaving, I could hear her making disparaging remarks to the people around (most probably about jeans\-clad, jacket\-wearing idiots and their ignorance of realities of life).

 I made way to the Heritage Fresh and there, as you have figured out now, the gourd was at half the price. That started me thinking. It is probably the presence of such price arbitration that makes people haggle. Once you suspect such an arbitration is possible, you start looking at every price with abundant caution. There is also the added angle of ‘being made a fool of’. A supermarket might make fools of everyone but being made a fool of, in isolation, is more difficult to handle. You are more cautious agreeing to a price.

 It also made me think of another angle. One of the arguments used against subsidized loans is that since the loan is subsidized, most of the times it is put to uses that give less than optimal returns. Thus, you are encouraging some one to engage in a less productive occupation by giving him a subsidized loan. Looked at this way, if there are enough people who are sensitive to the price arbitration between the two markets or if there is a possibility that the arbitration will become noticeable to a larger number of people and they will switch to supermarkets, may be we are making a mistake in supporting the ‘poor push\-cart guy’ with a price subsidy of sorts.

 Unfortunately or otherwise, there is one more angle that I can think of. In the excellent article titled [Kashmir: youth bulge, peace deficit](http://www.thehindu.com/opinion/lead/article602289.ece?homepage=true) in The Hindu today (I would strongly recommend a reading of this article, even if the current one has already bored you), Praveen Swami says the current political crisis in Kashmir has, among many others, an economic cause. He cites studies, focusing on English civil wars, European revolutions, rise of fascism in Germany and ethnic violence in Kenya, that point to a link between political violence and an increase in the number of young adult males in proportion to the total male population. In other words, too many young (or old, if you think about it) people with too little to do mean trouble.

 The point that Swami makes is quite compelling. Looked at this way, the subsidy part of the subsidized loans and the higher prices you pay in local markets, if it helps to keep a large population in employment, may not be that high a price to pay.

 All that I can conclude is that the complications seem a little too complex. Where you buy your bottle gourd has implications for the long\-term political stability of the country, if you are jobless enough to think through all this. Even if you are not, I would appreciate a little help, by way of your comments, in getting to terms with the complexity.

<!--
post-159
https://venugvgk.wordpress.com/2010/08/30/of-bottle-gourds-and-political-stability/
-->
