---
categories:
- books
date: '2010-04-25T18:09:47+05:30'
title: Chowringhee shortlisted for The Independent Foreign Fiction Prize 2010
---

My copy of Sankar’s ***Chowringhee*** was bought in Calcutta airport a couple of years ago. I picked it up not because I knew anything about it but because I was looking for a Bengali novel in English and it was visibly available.

 I read the book on the flight back…and I finished it later. It’s a complex tale of various characters and emotions set in a hotel, told through the eyes of a hotel clerk. While I enjoyed the book and would say it’s good, I would not attempt a review. It’s a complex book, as I already said, and I had read it only once. A braver soul reviewed the book in Hindu in 2007 [here.](http://www.thehindu.com/lr/2007/04/01/stories/2007040100160300.htm)

 I had read somewhere that this book is generally compared to Arthur Hailey’s The Hotel. I haven’t read The Hotel, so can’t say any thing more on that. As an aside, while Hailey fans talk about Money Changers and Airport, I personally think his Detective is a very good piece of crime fiction.

 Any way, ***chowringhee*** was written in 1962 and was translated in to English in 2007\. It has been nominated for The Independent Foreign Fiction Prize for 2010 – the first time that an Indian work has accomplished the feat. “Results“ are expected on May 13th. What struck me most was this line from the [article](http://www.thehindu.com/2010/04/21/stories/2010042156022000.htm) in The Hindu  :

  *Asked why the English translation came more than 40 years after it was first written, the author candidly remarked, “I suppose it was my middle class Bengali arrogance — why should I take my work to the world, the world should come to me.”*

 I love straight talk, especially the self\-deprecating kind. I also love it when one of the books I have read and appreciated gets recognized. For your information, I had read Slumdog Millionaire in its original avatar as ‘Q\&A’…I am a discerning reader, you know! By the way, Vikas Swarup’s next book, The Six Suspects, plain sucks!

<!--
post-57
https://venugvgk.wordpress.com/2010/04/25/chowringhee-shortlisted-for-the-independent-foreign-fiction-prize-2010/
-->
