---
title: Notes from Ambedkar's Columbia lecture on Caste
quartosync: "true"
filename: readings/sociology-ambedkar-1916.qmd
---
* "if Hindus migrate to other regions of earth, Indian caste will become a world problem." 


checking if this works over quartosync

Dr. Ambedkar sets up the importance of studying caste. Caste is a parceling out of a homogenous population. Various definitions of caste are then examined and the characteristics of caste proposed in the definitions are separated into results of caste system (ideas of pollution and purity, prohibition of inter-dining) and the essential nature of caste. It is emphasized that caste exists within a system of castes and not as an isolated entity. Between autogeny and endogamy, ==Endogamy is established as the essence of caste.== 

Then there is a discussion of the imposition of endogamy on the system of exogamy that is practiced in India. ==Practices of widow burning, imposing a life long widowhood and child marriage are child marriage as practices that were needed to prevent problem of surplus man and surplus woman, necessary to maintain endogamy and caste. ==

The nature of the argument - if you take a natural exogamous society, if we superimpose endogamy, what are the potential problems? What solutions can solve these problems? If we show that these solutions are present in the current society, we can argue that endogamy was created at a certain time. and that it did not come from a divine origin. 

Ambedkar makes this argument to attack the idea of divine origin - since the divine origin theory is where Brahminical position derives its strength. 

* traditions are honored because they are practiced. origin of the caste is the origin of the mechanism for endogamy. 

Society is composed not of individuals but classes. Caste is an enclosed class. 

How did classes end up becoming enclosed? Look at where the customs are most strictly observed, and it seems reasonable that Brahmins must have been the group that enclosed themselves first. 

however, one cannot say that a law giver like Manu or a group like brahmins created caste. It is impossible to do so for one person or one group. Shastras could also not have been able to create this. 

Most likely, Brahmins closed the doors of their class and became a caste. everyone else imitated. Everyone else imitated because Brahmins were the highest in prestige. They were the servants of good, semi-gods and demi-gods. 

Gabriel Tarde - three laws of imitation, hold good in the way caste is practiced. 

Some closed the door and the others found it closed against them. Anyone who violated caste rules was expelled and new castes were created. Fissiparous nature of the caste system. 

caste as a unit within the system of castes - a singular caste does not exist. it is always the plural castes. it is an unconscious growth in the life of a human society in peculiar circumstances and not a conscious command of the supreme authority. 


