---
categories:
- musings
date: '2011-11-23T15:16:34+05:30'
title: Are you happy?
---

**Are you happy?**

 I don’t know…

 **Okay, let’s get down to the details. Are you happy with your work life? The money you make and so on?**

 Yeah…I may not be the best out there but I am not the worst. I know I can do better but…Yeah, alright.

 **Are you happy with your family life?**

 Yes. I get along well with my wife; my son does well in school and is well adjusted. My parents or in\-laws are generally the non\-interfering kind. Yeah, I am happy. We have just come back from a vacation, you know!

 **Are you happy with your social life?**

 Yes. I have a good bunch of friends, even outside facebook. I get company for drinking every weekend.

 **Are you happy with yourself? How do people see you, how well you are doing overall and other such stuff…**

 Hmmm…I guess so. I am not a bad person or at least, no one told me so yet. I do reasonably well with family, friends, work and strangers.

 **Are you happy with how you have done till now?**

 I should be. I have done fairly decently considering where we started. I have done much better than my peer group.

 **Are you happy with your future prospects? How does it look?**

 Not bad…at least as far as I see…

 **Are you happy with the places you live in, work in or travel to?**

 Yeah, yeah. I am generally okay with such things.

 **So, are you happy?**

 Hmmm…it’s so difficult, man…I don’t know. May be I should be.

<!--
post-414
https://venugvgk.wordpress.com/2011/11/23/are-you-happy/
-->
