---
categories:
- books
date: '2010-04-18T13:50:51+05:30'
title: The Tale of a Tribute and two readings
---

When I read in the morning newspaper about Management Guru CK Prahlad passing away, I thought I would scour the internet in the hope of finding sufficiently amusing tributes…while one is not equipped intellectually to debate on the really relevant issues and one does not really know the luminary enough to feel any serious grief, one was confident that at least some of the people falling over themselves to write an important sounding tribute would provide the necessary entertainment.

 I needed not go farther than the [14th page](http://www.hindu.com/2010/04/18/stories/2010041861971400.htm) in the hallowed newspaper. While I am not going to the extent of annotating the tribute with “reading notes”, I am going to the extent of ‘copy\-pasting’ it for the fear that you will find navigating away from this page very difficult…captivating stuff here, no?

 **A master abstractionist**<br>
 **Lakshmi Narayanan**

 **It was at a technology conference in 2004 that Carly Fiorina, then CEO of Hewlett\-Packard, was delivering a keynote address. She was talking eloquently about HP’s experiment at Kuppam, Andhra Pradesh, where the company was empowering villagers through technology — distributing digital cameras and image printers that could be used to generate income. She called it “doing well by doing good” and went on to argue how the experiment had the potential to be a large revenue stream.**

 (Extremely sorry to interrupt but this is an absolute must know fact: Kuppam was the constituency of the erstwhile hi\-tech CM/CEO of AP – Mr. N. Chandrababu Naidu. In the world where railway ministers think nothing of ‘developing’ their own state, you can imagine the ‘developmental’ boost Kuppam would have got given Naidu was the CM for about 9 years – it’s these villagers that HP was ’empowering’ by distributing life\-changing products like cameras and printers)

 **Professor C.K. Prahalad was also a speaker at the conference and Carly’s speech seemed to fit in with a hypothesis he was working on. His subsequent work on “Fortune at the bottom of the Pyramid” was a great abstraction of the many examples and stories that corporate leaders have experienced.**

 **Once during a similar interaction with Professor Prahalad, I got an opportunity to talk about Cognizant and its growth story. I was elaborating on the company’s heritage, its image, its progress, its investment strategy and competitive pressures. It sounded almost like a big corporate pitch.**

 **Professor Prahalad simply said: “You have to differentiate your firm along two or three key aspects and make sure that you make disproportionate investments along those areas.” This was such a simple abstraction of what we, as a firm, should be doing strategically, that even today all of our investments are evaluated to see if they make a big difference to how we are differentiating ourselves in the marketplace.**

 **There are innumerable examples of his ability to abstract a theme in any given situation that can easily stand the test of time and any management theory. It is this ability that he put to use so effectively in defining a vision for India@75, as part of a large CII initiative. His prescription for a strong and resurgent India, simply put, is one of financial strength, technology excellence and moral authority. So simply put that his vision for India will live on.**

 **A management guru, a strategy consultant of the highest order and, above all, the Guru of Abstraction, Professor Prahalad will be missed by all in the corporate world. But his work will forever remain and guide leaders all over the world for a long time.**

 **(The writer is Vice\-Chairman, Cognizant.)** <br>
 Now, some useful reading.

 1\. [Romanticizing the Poor](http://www.ssireview.org/articles/entry/romanticizing_the_poor/#) – Aneel Karnani

 Market solutions to poverty are very much in vogue. These solutions, which include services and products targeting consumers at the “bottom of the pyramid,” portray poor people as creative entrepreneurs and discerning consumers. Yet this rosy view of poverty\-stricken people is not only wrong, but also harmful. It allows corporations, governments, and nonprofits to deny this vulnerable population the protections it needs. Romanticizing the poor also hobbles realistic interventions for alleviating poverty.

 2\. [Will the Real Social Entrepreneur Please Stand Up?](http://knowledge.wharton.upenn.edu/india/article.cfm?articleid=4445)

 How can you distinguish a business entrepreneur from a social entrepreneur? The answer is not as straightforward as it once was, says Abraham George, founder of The George Foundation, an NGO focused on poverty alleviation in southern India. Both are focused on profitability, margins and returns on investment. But social entrepreneurs go a step further, not only aiming to use their business activities to benefit society, but also involving society’s poorest members — now often referred to as the “Bottom of the Pyramid” — in efforts to reduce poverty and raise standards of living.

 That’s all well and good, explains George in this opinion piece, but it is increasingly unclear who “the poorest of the poor” are. Definitions vary widely, which often means marketing strategies, growth plans and even products and services are not catering to the world’s poorest people. In the worst cases, even well\-intentioned social entrepreneurs are misleading investors and the general public — and more importantly, letting down the billions of people living in poverty.

 Alright. I am off for a power nap. Profound thoughts, you know. Some Brain\-tissue restoration is called for.

<!--
post-26
https://venugvgk.wordpress.com/2010/04/18/the-tale-of-a-tribute/
-->
