---
categories:
- books
date: '2010-04-15T22:39:18+05:30'
title: Book Review – Ian Rankin
---

The first time I came across Ian Rankin was while reading an account of the interaction between him and Prakash Karat titled “crime fiction is about social inequality” in The Hindu [here](http://beta.thehindu.com/opinion/interview/article95782.ece). I know…but there are so many guys out there and it is hard to read them all.

 Recently, In Bangalore landmark I managed to find a Rankin book – strip jack. A couple of stores in Delhi, where I had tried earlier, did not have copies.

 It’s a good story. Fast paced too. The language is slightly different from the american one is so used to. The book is a suspense thriller. I don’t need to say more than that.

 In my library (a life time project, that…) I would put him along with Dick Francis and Harlen Coben (both of whom need to be written about separately).

 The common theme is that they do not need psychopaths to create a good crime story. All three pay close attention to detail and the stories usually have a good plot and a very good narration. Their heroes have some kind of self deprecating humor with a subtle hint of strong personal philosophy. While Dick Francis’s heroes are very well educated, Rankin’s Rebus is not. Francis writes in a race course setting while Coben uses sports as the backdrop. Rebus is your regular police detective.

 I particularly like use of lines like “I am caught between a cushion and a soft place” – Rebus thinking about how he has grown comfortable with his job and life.

 The other thing i liked was the mention of Genmorangie…in a pouring rain sequence, the inspector is offered a drink in a rich household, opens a cupboard and pours out a glass of Glenmorangie.This is the first time I have come across this drink mentioned in a book and this is one of the few drinks i have had that are mentioned in books – the others being Johny walker and Glenfiddich. I just love it when something like that happens. When I write a book, it is going to be full of people asking for a shot of McDowell’s Number One, Signature, Blender’s Pride or Royal Challenge. Yes…whiskey is my poison, if you please, and my birthday is on the day after tomorrow. Cheers!

<!--
post-19
https://venugvgk.wordpress.com/2010/04/15/book-review-ian-rankin/
-->
