---
title: Begumpura by Sant Ravidas
categories:
 - sociology
date: 2025-02-05
---
Born as a chamar, Ravidas saw himself as a “tanner now set free”. Preaching social equality and the assertion of identity, his two pronged approach of mystic realisation and political revolution became a powerful movement with several followers.

“aat-paat ke pher mah urjhai rahe sabh log
Mannukhta ku khat hai Ravidas jat ka rog

Everyone is trapped in the caste-system
Ravidas, humanity is being eaten up by the disease called caste”

The regal realm with the sorrowless name:
they call it Begumpura, a place with no pain,
No taxes or cares, none owns property there,
no wrongdoing, worry, terror, or torture.
Oh, my brother, I’ve come to take it as my own,
my distant home where everything is right.
That imperial kingdom is rich and secure,
where none are third or second – all are one;
They do this or that, they walk where they wish,
they stroll through fabled palaces unchallenged.
Oh, says Ravidas, a tanner now set free,
those who walk beside me are my friends.

Gail Omvedt in her book, Seeking Begumpura, writes

"It (begumpura poem) was an expression, in the early modern age, of a utopia, perhaps the first one in Indian literature. In some ways it seems to stand alone, yet it was a harbinger of the kind of social vision that would underlie all the later struggles and theorizing of anticaste inetllectuals. Begumpura was, for Ravidas, an imagined city, without geographical location, without a history: it was to be a later task to build it in space and time."


https://poetly.substack.com/p/begumpura