---
categories:
- book-review
- philosophy
date: '2023-08-02T12:01:14+05:30'
title: 'Wifedom: Mrs Orwell’s Invisible Life by Anna Funder – Review'
---

What a book…an excerpt is below.

A few thoughts:

1\. Women had it rough, and continue to have it rough, not withstanding the wokeism around. Many women themselves continue to be blind. And no man, NO MAN, is as good in this matter as he sounds. So let’s stop with the sealioning, and start seeing it around us.

2\. Affirms my belief that the men from previous generations had an easier life, got away with much, time and time again depending on the women. The most liberal, secular and woke sounding of them, were no exceptions. It contributed to the achievements of the highest achievers as well.

3\. The demands on this generation of men, who grew up watching the previous, and imagining a similar life for themselves, are much greater. This is a much needed change, but boy, is it hard!! Most of us never learn to deal with this and that is contributing to a lot of strife in families.

4\. The demands on men will only increase as we go, and rightly so. What we have, is the opportunity to prepare our children. We must prepare them well, if they are to have happier lives.

We will get no where by pretending all is well and hiding the struggles we are facing, and refusing to better prepare our children.

Now the excerpt:

“We think we’ve come a long way in 80 years, but statistically, there is an irrefutable, globally intransigent heterosexual norm that pervades across ethnicity, colour and class. Nowhere in the world do women have the same power, freedom, leisure or money as their male partners. Every society is built on the unpaid or underpaid work of women, an estimated $10\.9tn (£8\.5tn) of it a year. But to pay would be to redistribute wealth and power in a way that might defund and defang patriarchy.

Things in the rear\-view mirror are closer than they appear.

Which reminds me, of course, of my own, unseen, unsung conditions of production. As my husband says, with a wry smile: “You couldn’t have written this book without me.” And he’s absolutely right.

Wifedom: Mrs Orwell’s Invisible Life by Anna Funder is published on 17 August by Viking (£20\). “<br>


 Full review from the guardian [here](https://www.theguardian.com/books/2023/jul/30/my-hunt-for-eileen-george-orwell-erased-wife-anna-funder?CMP=fb_gu&utm_medium=Social&utm_source=Facebook&fbclid=IwAR33MtQw8ijxHqx8Sfrltw191ZTxYmy3reBkTrpkGsDPzxXBsPFLXC07YDE#Echobox=1690730991)

<!--
post-800
https://venugvgk.wordpress.com/2023/08/02/wifedom-mrs-orwells-invisible-life-by-anna-funder-review/
-->
